const Product =[
    {
      "id": 1,
      "country": "USA",
      "views": 2500,
      "category": "electronics",
      "brief": "Latest smartphone with advanced features.",
      "ratings": 4.7,
      "price": 699,
      "type": "featured",
      "image": "smartphone.jpg"
    },
    {
      "id": 2,
      "country": "Germany",
      "views": 1500,
      "category": "cars",
      "brief": "Luxury SUV with premium interiors.",
      "ratings": 4.8,
      "price": 50000,
      "type": "new",
      "image": "luxury_suv.jpg"
    },
    {
      "id": 3,
      "country": "UK",
      "views": 1300,
      "category": "restaurant",
      "brief": "Fine dining experience with gourmet meals.",
      "ratings": 4.6,
      "price": 100,
      "type": "sold",
      "image": "gourmet_meals.jpg"
    },
    {
      "id": 4,
      "country": "India",
      "views": 3000,
      "category": "education",
      "brief": "Online coding bootcamp for beginners.",
      "ratings": 4.9,
      "price": 500,
      "type": "featured",
      "image": "coding_bootcamp.jpg"
    },
    {
      "id": 5,
      "country": "Canada",
      "views": 500,
      "category": "health",
      "brief": "Fitness equipment for home workouts.",
      "ratings": 4.4,
      "price": 200,
      "type": "new",
      "image": "fitness_equipment.jpg"
    },
    {
      "id": 6,
      "country": "Australia",
      "views": 2400,
      "category": "grocery",
      "brief": "Organic vegetables delivered fresh.",
      "ratings": 4.5,
      "price": 50,
      "type": "sold",
      "image": "organic_vegetables.jpg"
    },
    {
      "id": 7,
      "country": "France",
      "views": 1100,
      "category": "property",
      "brief": "Luxury apartment in the city center.",
      "ratings": 4.7,
      "price": 150000,
      "type": "featured",
      "image": "luxury_apartment.jpg"
    },
    {
      "id": 8,
      "country": "Italy",
      "views": 900,
      "category": "food",
      "brief": "Authentic Italian pizza ingredients.",
      "ratings": 4.6,
      "price": 20,
      "type": "new",
      "image": "italian_pizza.jpg"
    },
    {
      "id": 9,
      "country": "Japan",
      "views": 2000,
      "category": "electronics",
      "brief": "4K smart TV with high-end display.",
      "ratings": 4.8,
      "price": 1200,
      "type": "sold",
      "image": "smart_tv.jpg"
    },
    {
      "id": 10,
      "country": "Brazil",
      "views": 600,
      "category": "health",
      "brief": "Natural supplements for boosting immunity.",
      "ratings": 4.2,
      "price": 40,
      "type": "new",
      "image": "natural_supplements.jpg"
    },
    {
      "id": 11,
      "country": "USA",
      "views": 3200,
      "category": "cars",
      "brief": "Electric sedan with long range battery.",
      "ratings": 4.9,
      "price": 45000,
      "type": "featured",
      "image": "electric_sedan.jpg"
    },
    {
      "id": 12,
      "country": "Germany",
      "views": 1700,
      "category": "food",
      "brief": "Gourmet chocolate assortment.",
      "ratings": 4.5,
      "price": 25,
      "type": "new",
      "image": "gourmet_chocolate.jpg"
    },
    {
      "id": 13,
      "country": "UK",
      "views": 1300,
      "category": "restaurant",
      "brief": "Best seafood restaurant in town.",
      "ratings": 4.6,
      "price": 80,
      "type": "sold",
      "image": "seafood_restaurant.jpg"
    },
    {
      "id": 14,
      "country": "India",
      "views": 3100,
      "category": "grocery",
      "brief": "Daily essentials delivered to your door.",
      "ratings": 4.4,
      "price": 30,
      "type": "featured",
      "image": "daily_essentials.jpg"
    },
    {
      "id": 15,
      "country": "Canada",
      "views": 700,
      "category": "education",
      "brief": "Language learning courses for beginners.",
      "ratings": 4.7,
      "price": 150,
      "type": "new",
      "image": "language_courses.jpg"
    },
    {
      "id": 16,
      "country": "Australia",
      "views": 2400,
      "category": "electronics",
      "brief": "Wireless headphones with noise cancellation.",
      "ratings": 4.8,
      "price": 200,
      "type": "sold",
      "image": "wireless_headphones.jpg"
    },
    {
      "id": 17,
      "country": "France",
      "views": 1200,
      "category": "health",
      "brief": "Skin care products made with natural ingredients.",
      "ratings": 4.5,
      "price": 70,
      "type": "featured",
      "image": "skin_care.jpg"
    },
    {
      "id": 18,
      "country": "Italy",
      "views": 950,
      "category": "food",
      "brief": "Pasta kit for authentic Italian cooking.",
      "ratings": 4.6,
      "price": 30,
      "type": "new",
      "image": "pasta_kit.jpg"
    },
    {
      "id": 19,
      "country": "Japan",
      "views": 2200,
      "category": "cars",
      "brief": "Compact city car with hybrid technology.",
      "ratings": 4.8,
      "price": 22000,
      "type": "sold",
      "image": "compact_car.jpg"
    },
    {
      "id": 20,
      "country": "Brazil",
      "views": 650,
      "category": "grocery",
      "brief": "Fresh tropical fruits available daily.",
      "ratings": 4.4,
      "price": 60,
      "type": "new",
      "image": "tropical_fruits.jpg"
    },
    {
      "id": 21,
      "country": "USA",
      "views": 3300,
      "category": "property",
      "brief": "Spacious villa with a private pool.",
      "ratings": 4.9,
      "price": 500000,
      "type": "featured",
      "image": "spacious_villa.jpg"
    },
    {
      "id": 22,
      "country": "Germany",
      "views": 1800,
      "category": "restaurant",
      "brief": "Cozy café with homemade desserts.",
      "ratings": 4.5,
      "price": 30,
      "type": "new",
      "image": "cozy_cafe.jpg"
    },
    {
      "id": 23,
      "country": "UK",
      "views": 1400,
      "category": "electronics",
      "brief": "Smartwatch with fitness tracking features.",
      "ratings": 4.6,
      "price": 250,
      "type": "sold",
      "image": "smartwatch.jpg"
    },
    {
      "id": 24,
      "country": "India",
      "views": 3200,
      "category": "education",
      "brief": "Digital marketing course with certification.",
      "ratings": 4.9,
      "price": 300,
      "type": "featured",
      "image": "marketing_course.jpg"
    },
    {
      "id": 25,
      "country": "Canada",
      "views": 800,
      "category": "grocery",
      "brief": "Organic dairy products from local farms.",
      "ratings": 4.5,
      "price": 40,
      "type": "new",
      "image": "organic_dairy.jpg"
    },
    {
      "id": 26,
      "country": "Australia",
      "views": 2500,
      "category": "health",
      "brief": "Yoga equipment for home practice.",
      "ratings": 4.7,
      "price": 100,
      "type": "sold",
      "image": "yoga_equipment.jpg"
    },
    {
      "id": 27,
      "country": "France",
      "views": 1300,
      "category": "food",
      "brief": "French pastries made with fresh ingredients.",
      "ratings": 4.6,
      "price": 15,
      "type": "featured",
      "image": "french_pastries.jpg"
    },
    {
      "id": 28,
      "country": "Italy",
      "views": 980,
      "category": "restaurant",
      "brief": "Traditional Italian trattoria.",
      "ratings": 4.6,
      "price": 70,
      "type": "new",
      "image": "italian_trattoria.jpg"
    },
    {
      "id": 29,
      "country": "Japan",
      "views": 2300,
      "category": "cars",
      "brief": "Luxury sports car with cutting-edge design.",
      "ratings": 4.9,
      "price": 120000,
      "type": "sold",
      "image": "sports_car.jpg"
    },
    {
      "id": 30,
      "country": "Brazil",
      "views": 750,
      "category": "electronics",
      "brief": "High-performance gaming laptop.",
      "ratings": 4.8,
      "price": 1500,
      "type": "new",
      "image": "gaming_laptop.jpg"
    },
    {
      "id": 31,
      "country": "USA",
      "views": 3400,
      "category": "education",
      "brief": "Masterclass on web development.",
      "ratings": 4.9,
      "price": 600,
      "type": "featured",
      "image": "web_dev_masterclass.jpg"
    },
    {
      "id": 32,
      "country": "Germany",
      "views": 1900,
      "category": "grocery",
      "brief": "Imported cheese selection from Europe.",
      "ratings": 4.7,
      "price": 80,
      "type": "new",
      "image": "imported_cheese.jpg"
    },
    {
      "id": 33,
      "country": "UK",
      "views": 1500,
      "category": "health",
      "brief": "Workout supplements for building muscle.",
      "ratings": 4.5,
      "price": 60,
      "type": "sold",
      "image": "workout_supplements.jpg"
    },
    {
      "id": 34,
      "country": "India",
      "views": 3300,
      "category": "property",
      "brief": "Modern apartment in a prime location.",
      "ratings": 4.8,
      "price": 200000,
      "type": "featured",
      "image": "modern_apartment.jpg"
    },
    {
      "id": 35,
      "country": "Canada",
      "views": 850,
      "category": "restaurant",
      "brief": "Top-rated steakhouse with premium cuts.",
      "ratings": 4.7,
      "price": 90,
      "type": "new",
      "image": "steakhouse.jpg"
    },
    {
      "id": 36,
      "country": "Australia",
      "views": 2600,
      "category": "electronics",
      "brief": "Home automation system for smart homes.",
      "ratings": 4.9,
      "price": 500,
      "type": "sold",
      "image": "home_automation.jpg"
    },
    {
      "id": 37,
      "country": "France",
      "views": 1400,
      "category": "grocery",
      "brief": "Freshly baked artisan bread.",
      "ratings": 4.6,
      "price": 10,
      "type": "featured",
      "image": "artisan_bread.jpg"
    },
    {
      "id": 38,
      "country": "Italy",
      "views": 1000,
      "category": "education",
      "brief": "Mastering Italian cuisine online course.",
      "ratings": 4.9,
      "price": 200,
      "type": "new",
      "image": "italian_cuisine_course.jpg"
    },
    {
      "id": 39,
      "country": "Japan",
      "views": 2400,
      "category": "health",
      "brief": "Wellness retreats for relaxation and rejuvenation.",
      "ratings": 4.8,
      "price": 3000,
      "type": "sold",
      "image": "wellness_retreat.jpg"
    },
    {
      "id": 40,
      "country": "Brazil",
      "views": 800,
      "category": "restaurant",
      "brief": "Best Brazilian barbecue in town.",
      "ratings": 4.7,
      "price": 60,
      "type": "new",
      "image": "brazilian_bbq.jpg"
    },
    {
      "id": 41,
      "country": "USA",
      "views": 3500,
      "category": "cars",
      "brief": "Luxury convertible with advanced features.",
      "ratings": 4.9,
      "price": 75000,
      "type": "featured",
      "image": "luxury_convertible.jpg"
    },
    {
      "id": 42,
      "country": "Germany",
      "views": 2000,
      "category": "food",
      "brief": "Delicious vegan meal prep service.",
      "ratings": 4.5,
      "price": 80,
      "type": "new",
      "image": "vegan_meal_prep.jpg"
    },
    {
      "id": 43,
      "country": "UK",
      "views": 1600,
      "category": "property",
      "brief": "Charming cottage in the countryside.",
      "ratings": 4.7,
      "price": 350000,
      "type": "sold",
      "image": "charming_cottage.jpg"
    },
    {
      "id": 44,
      "country": "India",
      "views": 3400,
      "category": "electronics",
      "brief": "Smart home security system.",
      "ratings": 4.8,
      "price": 400,
      "type": "featured",
      "image": "home_security.jpg"
    },
    {
      "id": 45,
      "country": "Canada",
      "views": 900,
      "category": "health",
      "brief": "Personalized fitness coaching sessions.",
      "ratings": 4.6,
      "price": 120,
      "type": "new",
      "image": "fitness_coaching.jpg"
    },
    {
      "id": 46,
      "country": "Australia",
      "views": 2700,
      "category": "grocery",
      "brief": "Fresh seafood delivery from local fishermen.",
      "ratings": 4.9,
      "price": 100,
      "type": "sold",
      "image": "seafood_delivery.jpg"
    },
    {
      "id": 47,
      "country": "France",
      "views": 1500,
      "category": "restaurant",
      "brief": "Elegant French restaurant with a seasonal menu.",
      "ratings": 4.7,
      "price": 120,
      "type": "new",
      "image": "french_restaurant.jpg"
    },
    {
      "id": 48,
      "country": "Italy",
      "views": 1050,
      "category": "food",
      "brief": "Authentic gelato with fresh ingredients.",
      "ratings": 4.8,
      "price": 15,
      "type": "sold",
      "image": "authentic_gelato.jpg"
    },
    {
      "id": 49,
      "country": "Japan",
      "views": 2500,
      "category": "education",
      "brief": "Learn Japanese through interactive lessons.",
      "ratings": 4.9,
      "price": 400,
      "type": "featured",
      "image": "japanese_lessons.jpg"
    },
    {
      "id": 50,
      "country": "Brazil",
      "views": 850,
      "category": "property",
      "brief": "Beachfront condo with ocean views.",
      "ratings": 4.7,
      "price": 300000,
      "type": "new",
      "image": "beachfront_condo.jpg"
    }
  ]
  
  
export default Product  