const Product =[
    {
      "id": 1,
      "country": "USA",
      "views": 2500,
      "category": "electronics",
      "brief": "Latest smartphone with advanced features.",
      "ratings": 4.7,
      "price": 699,
      "type": "featured",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvmQCnLLbDR-f1_1_GD2yC8dGVG3OZfAkRCQ&s"
    },
    {
      "id": 2,
      "country": "Germany",
      "views": 1500,
      "category": "cars",
      "brief": "Luxury SUV with premium interiors.",
      "ratings": 4.8,
      "price": 50000,
      "type": "new",
      "image": "https://static.vecteezy.com/system/resources/thumbnails/023/192/562/small_2x/sport-car-running-on-the-road-in-future-city-created-with-generative-ai-free-photo.jpg"
    },
    {
      "id": 3,
      "country": "UK",
      "views": 1300,
      "category": "restaurant",
      "brief": "Fine dining experience with gourmet meals.",
      "ratings": 4.6,
      "price": 100,
      "type": "sold",
      "image": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cmVzdGF1cmFudHxlbnwwfHwwfHx8MA%3D%3D"
    },
    {
      "id": 4,
      "country": "India",
      "views": 3000,
      "category": "education",
      "brief": "Online coding bootcamp for beginners.",
      "ratings": 4.9,
      "price": 500,
      "type": "featured",
      "image": "https://static.wixstatic.com/media/65246d_c7bd3ba476fb4191af59a11494ad027f~mv2.jpg/v1/fill/w_820,h_460,al_c,q_85/65246d_c7bd3ba476fb4191af59a11494ad027f~mv2.jpg"
    },
    {
      "id": 5,
      "country": "Canada",
      "views": 500,
      "category": "health",
      "brief": "Fitness equipment for home workouts.",
      "ratings": 4.4,
      "price": 200,
      "type": "new",
      "image": "https://www.homefitnesscode.com/cdn/shop/articles/various_fitness_equipment_2000x.jpg?v=1622715620"
    },
    {
      "id": 6,
      "country": "Australia",
      "views": 2400,
      "category": "grocery",
      "brief": "Organic vegetables delivered fresh.",
      "ratings": 4.5,
      "price": 50,
      "type": "sold",
      "image": "https://png.pngtree.com/png-vector/20230905/ourmid/pngtree-composition-with-grocery-products-in-shopping-basket-diet-png-image_9948113.png"
    },
    {
      "id": 7,
      "country": "France",
      "views": 1100,
      "category": "property",
      "brief": "Luxury apartment in the city center.",
      "ratings": 4.7,
      "price": 150000,
      "type": "featured",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2heEAr62IA8aYpqsaA_EiI-cMDzmaKRZGIA&s"
    },
    {
      "id": 8,
      "country": "Italy",
      "views": 900,
      "category": "food",
      "brief": "Authentic Italian pizza ingredients.",
      "ratings": 4.6,
      "price": 20,
      "type": "new",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIibPbOeDQQscm9g-fDNdCvROokQJukg8nYQ&s"
    },
    {
      "id": 9,
      "country": "Japan",
      "views": 2000,
      "category": "electronics",
      "brief": "4K smart TV with high-end display.",
      "ratings": 4.8,
      "price": 1200,
      "type": "sold",
      "image": "https://aws-obg-image-lb-1.tcl.com/content/dam/brandsite/global/news/5.jpg"
    },
    {
      "id": 10,
      "country": "Brazil",
      "views": 600,
      "category": "health",
      "brief": "Natural supplements for boosting immunity.",
      "ratings": 4.2,
      "price": 40,
      "type": "new",
      "image": "https://www.hollywoodpresbyterian.com/wp-content/uploads/2023/02/blog-immune.jpg"
    },
    {
      "id": 11,
      "country": "USA",
      "views": 3200,
      "category": "cars",
      "brief": "Electric sedan with long range battery.",
      "ratings": 4.9,
      "price": 45000,
      "type": "featured",
      "image": "https://imgd.aeplcdn.com/370x208/n/cw/ec/130591/fronx-exterior-right-front-three-quarter-109.jpeg?isig=0&q=80"
    },
    {
      "id": 12,
      "country": "Germany",
      "views": 1700,
      "category": "food",
      "brief": "Gourmet chocolate assortment.",
      "ratings": 4.5,
      "price": 25,
      "type": "new",
      "image": "https://www.thespruceeats.com/thmb/FhHcgQni8lgV0griUeDJMTAszxI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/chocolate_hero1-d62e5444a8734f8d8fe91f5631d51ca5.jpg"
    },
    {
      "id": 13,
      "country": "UK",
      "views": 1300,
      "category": "restaurant",
      "brief": "Best seafood restaurant in town.",
      "ratings": 4.6,
      "price": 80,
      "type": "sold",
      "image": "https://t3.ftcdn.net/jpg/03/24/73/92/360_F_324739203_keeq8udvv0P2h1MLYJ0GLSlTBagoXS48.jpg"
    },
    {
      "id": 14,
      "country": "India",
      "views": 3100,
      "category": "grocery",
      "brief": "Daily essentials delivered to your door.",
      "ratings": 4.4,
      "price": 30,
      "type": "featured",
      "image": "https://thumbs.dreamstime.com/b/set-grocery-items-vegetables-canned-food-pasta-oil-cereal-green-eco-shopping-bag-white-background-top-view-181827099.jpg"
    },
    {
      "id": 15,
      "country": "Canada",
      "views": 700,
      "category": "education",
      "brief": "Language learning courses for beginners.",
      "ratings": 4.7,
      "price": 150,
      "type": "new",
      "image": "https://www.aihr.com/wp-content/uploads/learning-vs-training-cover.png"
    },
    {
      "id": 16,
      "country": "Australia",
      "views": 2400,
      "category": "electronics",
      "brief": "Wireless headphones with noise cancellation.",
      "ratings": 4.8,
      "price": 200,
      "type": "sold",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBpiJFhKDwdsuAmso9FJ1DSckOdhI_VNhTdA&s"
    },
    {
      "id": 17,
      "country": "France",
      "views": 1200,
      "category": "health",
      "brief": "Skin care products made with natural ingredients.",
      "ratings": 4.5,
      "price": 70,
      "type": "featured",
      "image": "https://puresense.co.in/cdn/shop/articles/1_d95e1a0b-2e3f-4a0b-a604-6b2eef1d498c.jpg?v=1668491116"
    },
    {
      "id": 18,
      "country": "Italy",
      "views": 950,
      "category": "food",
      "brief": "Pasta kit for authentic Italian cooking.",
      "ratings": 4.6,
      "price": 30,
      "type": "new",
      "image": "https://pastaevangelists.com/cdn/shop/products/gifts-by-pasta-evangelists-classic-pasta-making-kit-29660967239789@2x.jpg?v=1686242777"
    },
    {
      "id": 19,
      "country": "Japan",
      "views": 2200,
      "category": "cars",
      "brief": "Compact city car with hybrid technology.",
      "ratings": 4.8,
      "price": 22000,
      "type": "sold",
      "image": "https://imageio.forbes.com/specials-images/imageserve/5d35eacaf1176b0008974b54/0x0.jpg?format=jpg&crop=4560,2565,x790,y784,safe&height=900&width=1600&fit=bounds"
    },
    {
      "id": 20,
      "country": "Brazil",
      "views": 650,
      "category": "grocery",
      "brief": "Fresh tropical fruits available daily.",
      "ratings": 4.4,
      "price": 60,
      "type": "new",
      "image": "https://www.shutterstock.com/image-photo/assorted-fresh-groceries-falling-paper-260nw-2259056413.jpg"
    },
    {
      "id": 21,
      "country": "USA",
      "views": 3300,
      "category": "property",
      "brief": "Spacious villa with a private pool.",
      "ratings": 4.9,
      "price": 500000,
      "type": "featured",
      "image": "https://t4.ftcdn.net/jpg/03/70/64/43/360_F_370644357_MDF4UXLAXTyyi2OyuK66tWW9cA2f8svL.jpg"
    },
    {
      "id": 22,
      "country": "Germany",
      "views": 1800,
      "category": "restaurant",
      "brief": "Cozy café with homemade desserts.",
      "ratings": 4.5,
      "price": 30,
      "type": "new",
      "image": "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
    },
    {
      "id": 23,
      "country": "UK",
      "views": 1400,
      "category": "electronics",
      "brief": "Smartwatch with fitness tracking features.",
      "ratings": 4.6,
      "price": 250,
      "type": "sold",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKODD4LTCYKpJTC5ET6TF2_F25yDHGJ6A-xg&s"
    },
    {
      "id": 24,
      "country": "India",
      "views": 3200,
      "category": "education",
      "brief": "Digital marketing course with certification.",
      "ratings": 4.9,
      "price": 300,
      "type": "featured",
      "image": "https://t4.ftcdn.net/jpg/09/28/79/89/360_F_928798982_PVkrws74x6Z0KcgQrhoRqpHPTiWPvPXu.jpg"
    },
    {
      "id": 25,
      "country": "Canada",
      "views": 800,
      "category": "grocery",
      "brief": "Organic dairy products from local farms.",
      "ratings": 4.5,
      "price": 40,
      "type": "new",
      "image": "https://media.istockphoto.com/id/915312176/vector/canned-goods-in-a-row.jpg?s=612x612&w=0&k=20&c=HgnYqvDLumZj0OwpV38TbNym4mJXs9vF5ESAKfcgDFo="
    },
    {
      "id": 26,
      "country": "Australia",
      "views": 2500,
      "category": "health",
      "brief": "Yoga equipment for home practice.",
      "ratings": 4.7,
      "price": 100,
      "type": "sold",
      "image": "https://images.everydayhealth.com/images/healthy-living/fitness/guide-to-yoga-props-00-722x406.tmb-0.jpg?sfvrsn=b2a5debe_1"
    },
    {
      "id": 27,
      "country": "France",
      "views": 1300,
      "category": "food",
      "brief": "French pastries made with fresh ingredients.",
      "ratings": 4.6,
      "price": 15,
      "type": "featured",
      "image": "https://media.istockphoto.com/id/497959594/photo/fresh-cakes.jpg?s=612x612&w=0&k=20&c=T1vp7QPbg6BY3GE-qwg-i_SqVpstyHBMIwnGakdTTek="
    },
    {
      "id": 28,
      "country": "Italy",
      "views": 980,
      "category": "restaurant",
      "brief": "Traditional Italian trattoria.",
      "ratings": 4.6,
      "price": 70,
      "type": "new",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEyrf03r2z27YcHSYguNgXmgKV5dSDjGsijw&s"
    },
    {
      "id": 29,
      "country": "Japan",
      "views": 2300,
      "category": "cars",
      "brief": "Luxury sports car with cutting-edge design.",
      "ratings": 4.9,
      "price": 120000,
      "type": "sold",
      "image": "https://cdni.autocarindia.com/utils/ImageResizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Grand-i10-Nios-200120231541.jpg"
    },
    {
      "id": 30,
      "country": "Brazil",
      "views": 750,
      "category": "electronics",
      "brief": "High-performance gaming laptop.",
      "ratings": 4.8,
      "price": 1500,
      "type": "new",
      "image": "https://cdn.pixabay.com/photo/2020/10/21/18/07/laptop-5673901_1280.jpg"
    },
    {
      "id": 31,
      "country": "USA",
      "views": 3400,
      "category": "education",
      "brief": "Masterclass on web development.",
      "ratings": 4.9,
      "price": 600,
      "type": "featured",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIfIeQegr--KT2kc22zTpG6yynJW_YiaT1DA&s"
    },
    {
      "id": 32,
      "country": "Germany",
      "views": 1900,
      "category": "grocery",
      "brief": "Imported cheese selection from Europe.",
      "ratings": 4.7,
      "price": 80,
      "type": "new",
      "image": "https://i0.wp.com/www.lovelocal.in/blog/wp-content/uploads/2024/06/Grocery-Restock-WA.jpg?fit=640%2C640&ssl=1"
    },
    {
      "id": 33,
      "country": "UK",
      "views": 1500,
      "category": "health",
      "brief": "Workout supplements for building muscle.",
      "ratings": 4.5,
      "price": 60,
      "type": "sold",
      "image": "https://media.istockphoto.com/id/636191848/photo/dumbbell-and-yoga-mat-on-wood-table.jpg?s=612x612&w=0&k=20&c=SELP8KSRmx2noiRcze_5FAgtR_RlZil84Q4Xo8s9c0Y="
    },
    {
      "id": 34,
      "country": "India",
      "views": 3300,
      "category": "property",
      "brief": "Modern apartment in a prime location.",
      "ratings": 4.8,
      "price": 200000,
      "type": "featured",
      "image": "https://media.istockphoto.com/id/1393537665/photo/modern-townhouse-design.jpg?s=612x612&w=0&k=20&c=vgQesOXDRzz0UfOZxmUtE-rFe75YgA9GvkKS8eeeumE="
    },
    {
      "id": 35,
      "country": "Canada",
      "views": 850,
      "category": "restaurant",
      "brief": "Top-rated steakhouse with premium cuts.",
      "ratings": 4.7,
      "price": 90,
      "type": "new",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRawkOEYbpqXEwuK-T5CjqawEiWFwzVnM1HOw&s"
    },
    {
      "id": 36,
      "country": "Australia",
      "views": 2600,
      "category": "electronics",
      "brief": "Home automation system for smart homes.",
      "ratings": 4.9,
      "price": 500,
      "type": "sold",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPTRUXwN5Kdra8mycVmeGXrohno38vgwjtVA&s"
    },
    {
      "id": 37,
      "country": "France",
      "views": 1400,
      "category": "grocery",
      "brief": "Freshly baked artisan bread.",
      "ratings": 4.6,
      "price": 10,
      "type": "featured",
      "image": "https://c8.alamy.com/comp/HWJC85/bread-in-a-dutch-supermarket-HWJC85.jpg"
    },
    {
      "id": 38,
      "country": "Italy",
      "views": 1000,
      "category": "education",
      "brief": "Mastering Italian cuisine online course.",
      "ratings": 4.9,
      "price": 200,
      "type": "new",
      "image": "https://www.success.com/wp-content/uploads/legacy/sites/default/files/main/blogposts/cookgrowshare_3.jpg"
    },
    {
      "id": 39,
      "country": "Japan",
      "views": 2400,
      "category": "health",
      "brief": "Wellness retreats for relaxation and rejuvenation.",
      "ratings": 4.8,
      "price": 3000,
      "type": "sold",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiegDLCfkmkgok6KhBsltME3aIbOWlMUNW0w&s"
    },
    {
      "id": 40,
      "country": "Brazil",
      "views": 800,
      "category": "restaurant",
      "brief": "Best Brazilian barbecue in town.",
      "ratings": 4.7,
      "price": 60,
      "type": "new",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSe3CYAVTn5PuJcp-lQp0fRoNiMrbT189aEyw&s"
    },
    {
      "id": 41,
      "country": "USA",
      "views": 3500,
      "category": "cars",
      "brief": "Luxury convertible with advanced features.",
      "ratings": 4.9,
      "price": 75000,
      "type": "featured",
      "image": "https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/images/car-reviews/first-drives/legacy/rolls_royce_phantom_top_10.jpg?itok=XjL9f1tx"
    },
    {
      "id": 42,
      "country": "Germany",
      "views": 2000,
      "category": "food",
      "brief": "Delicious vegan meal prep service.",
      "ratings": 4.5,
      "price": 80,
      "type": "new",
      "image": "https://images.immediate.co.uk/production/volatile/sites/30/2023/01/Ponzu-tofu-poke-bowl-8733c67.jpg?quality=90&resize=440,400"
    },
    {
      "id": 43,
      "country": "UK",
      "views": 1600,
      "category": "property",
      "brief": "Charming cottage in the countryside.",
      "ratings": 4.7,
      "price": 350000,
      "type": "sold",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3oT_3JMH5ZUQphyQ4hD6pULb-SkwFHcx1gg&s"
    },
    {
      "id": 44,
      "country": "India",
      "views": 3400,
      "category": "electronics",
      "brief": "Smart home security system.",
      "ratings": 4.8,
      "price": 400,
      "type": "featured",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQa6e1Qs-xILEltTNQLoSDbRpyYuzApCfK8SA&s"
    },
    {
      "id": 45,
      "country": "Canada",
      "views": 900,
      "category": "health",
      "brief": "Personalized fitness coaching sessions.",
      "ratings": 4.6,
      "price": 120,
      "type": "new",
      "image": "https://www.nextinsurance.com/wp-content/uploads/2020/04/April_2020_5-802x454.jpg"
    },
    {
      "id": 46,
      "country": "Australia",
      "views": 2700,
      "category": "grocery",
      "brief": "Fresh seafood delivery from local fishermen.",
      "ratings": 4.9,
      "price": 100,
      "type": "sold",
      "image": "https://media.istockphoto.com/id/1156027693/photo/fresh-salmon-steak-with-a-variety-of-seafood-and-herbs.jpg?s=612x612&w=0&k=20&c=FnY31V37yG5Ip4ejRttubUHBS8PPTaZfHHukDsEDjc0="
    },
    {
      "id": 47,
      "country": "France",
      "views": 1500,
      "category": "restaurant",
      "brief": "Elegant French restaurant with a seasonal menu.",
      "ratings": 4.7,
      "price": 120,
      "type": "new",
      "image": "https://cdn10.bostonmagazine.com/wp-content/uploads/sites/2/2023/10/beacon_restaurants-2.jpg"
    },
    {
      "id": 48,
      "country": "Italy",
      "views": 1050,
      "category": "food",
      "brief": "Authentic gelato with fresh ingredients.",
      "ratings": 4.8,
      "price": 15,
      "type": "sold",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuE1lV5Z-gcO-JwBAOR_MTJc4rtxifht7NBw&s"
    },
    {
      "id": 49,
      "country": "Japan",
      "views": 2500,
      "category": "education",
      "brief": "Learn Japanese through interactive lessons.",
      "ratings": 4.9,
      "price": 400,
      "type": "featured",
      "image": "https://thumbs.dreamstime.com/b/kid-creativity-education-concept-child-learning-art-mathematics-formula-school-boy-ideas-black-chalk-board-57852601.jpg"
    },
    {
      "id": 50,
      "country": "Brazil",
      "views": 850,
      "category": "property",
      "brief": "Beachfront condo with ocean views.",
      "ratings": 4.7,
      "price": 300000,
      "type": "new",
      "image": "https://robbreport.com/wp-content/uploads/2018/11/8-1_56_58-n-la-senda-dr.jpg"
    }
  ]
  
  
export default Product  