const PropertyData = 

[
    {
      "id": 1,
      "description": "Dhaka, Bangladesh - Modern 3-bedroom apartment in Gulshan.",
      "permission": "yes",
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 500,
      "bedroom": 3,
      "bathroom": 2,
      "square_fit": 1200,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTta0XsQDICRBsKhhCivnBCRkL3KDsfAc66jg&s"
    },
    {
      "id": 2,
      "description": "Toronto, Canada - Luxury penthouse overlooking Lake Ontario.",
      "permission": null,
      "authority": "verified",
      "type": "penthouse",
      "rent_per_month": 2500,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 2200,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcqgtsGNO_IfzYM6VPS8lNikw4JWE-gsEBjQ&s"
    },
    {
      "id": 3,
      "description": "Lagos, Nigeria - Spacious 5-bedroom duplex in Victoria Island.",
      "permission": "yes",
      "authority": null,
      "type": "duplex",
      "rent_per_month": 1500,
      "bedroom": 5,
      "bathroom": 4,
      "square_fit": 3000,
      "image": "https://media.istockphoto.com/id/1319269543/photo/new-homes-on-a-quiet-street-in-raleigh-nc.jpg?s=612x612&w=0&k=20&c=qaRMP-xgYqFAXR9aTpiG0dtkyqPhJiTAovvxyG1AxvM="
    },
    {
      "id": 4,
      "description": "New York, US - Stylish 2-bedroom apartment in Manhattan.",
      "permission": "yes",
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 3200,
      "bedroom": 2,
      "bathroom": 2,
      "square_fit": 1000,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMp4Ey9UGu2sVrvNkgoIK2OMKpDM0tPbhodA&s"
    },
    {
      "id": 5,
      "description": "London, UK - Elegant 3-bedroom luxury flat in Kensington.",
      "permission": null,
      "authority": "verified",
      "type": "luxury",
      "rent_per_month": 4500,
      "bedroom": 3,
      "bathroom": 3,
      "square_fit": 1800,
      "image": "https://www.loans.com.au/dA/9de8aa8d51/what-factors-affect-property-value.png"
    },
    {
      "id": 6,
      "description": "Chittagong, Bangladesh - Cozy 2-bedroom apartment in Agrabad.",
      "permission": "yes",
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 300,
      "bedroom": 2,
      "bathroom": 1,
      "square_fit": 900,
      "image": "https://sbnri.com/blog/wp-content/uploads/2021/07/NRI-Property-In-India.jpg"
    },
    {
      "id": 7,
      "description": "Vancouver, Canada - Modern duplex with garden view.",
      "permission": "yes",
      "authority": null,
      "type": "duplex",
      "rent_per_month": 1800,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 2500,
      "image": "https://images.unsplash.com/photo-1605146769289-440113cc3d00?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHx8MA%3D%3D"
    },
    {
      "id": 8,
      "description": "Abuja, Nigeria - Contemporary 4-bedroom apartment in Garki.",
      "permission": null,
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 1200,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 2000,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWwZGWnpdqGGBcZm1jkl1v4KboQYjjNhb9Ag&s"
    },
    {
      "id": 9,
      "description": "San Francisco, US - Penthouse with Golden Gate views.",
      "permission": "yes",
      "authority": "verified",
      "type": "penthouse",
      "rent_per_month": 5200,
      "bedroom": 3,
      "bathroom": 2,
      "square_fit": 2100,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLUwabE1G0Nz__-0S7T6of4xCsM1h_JXsD3g&s"
    },
    {
      "id": 10,
      "description": "Birmingham, UK - Newly renovated duplex near city center.",
      "permission": "yes",
      "authority": null,
      "type": "duplex",
      "rent_per_month": 1300,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 1700,
      "image": "https://cdn.pixabay.com/photo/2017/07/08/02/16/house-2483336_640.jpg"
    },
    {
      "id": 11,
      "description": "Dhaka, Bangladesh - Luxury 4-bedroom penthouse in Banani.",
      "permission": "yes",
      "authority": "verified",
      "type": "penthouse",
      "rent_per_month": 2000,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 2500,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRw8gEtCm5H68YINlhcCNLGE_wmLvt9eZ3Aug&s"
    },
    {
      "id": 12,
      "description": "Montreal, Canada - 3-bedroom apartment near downtown.",
      "permission": "yes",
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 1400,
      "bedroom": 3,
      "bathroom": 2,
      "square_fit": 1100,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRn_UV-pluRPIqTSt9DkFq94LfvCWDEJlCfAw&s"
    },
    {
      "id": 13,
      "description": "Ibadan, Nigeria - 2-bedroom apartment in a gated community.",
      "permission": null,
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 600,
      "bedroom": 2,
      "bathroom": 2,
      "square_fit": 850,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEQQZn5huiz-zIWrdjDZulAdG7gaXQozYELQ&s"
    },
    {
      "id": 14,
      "description": "Los Angeles, US - Chic 2-bedroom luxury apartment in Beverly Hills.",
      "permission": "yes",
      "authority": "verified",
      "type": "luxury",
      "rent_per_month": 4800,
      "bedroom": 2,
      "bathroom": 2,
      "square_fit": 1300,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFd6y6oIdtvqknInDukHXF-wrAnhofrItt-Q&s"
    },
    {
      "id": 15,
      "description": "Manchester, UK - Spacious building with multiple units for rent.",
      "permission": null,
      "authority": "verified",
      "type": "building",
      "rent_per_month": 6500,
      "bedroom": 10,
      "bathroom": 8,
      "square_fit": 4500,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQf9FXwoX6TFCR6w5JFAk5PELHZhBAYUIqfg&s"
    },
    {
      "id": 16,
      "description": "Rajshahi, Bangladesh - Affordable 3-bedroom apartment in a quiet area.",
      "permission": "yes",
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 350,
      "bedroom": 3,
      "bathroom": 2,
      "square_fit": 1150,
      "image": "https://assets.helloaddress.com/propertyImages/2024/July/thumb_property_P956317_66a24319cc24f.jpg"
    },
    {
      "id": 17,
      "description": "Calgary, Canada - Family-friendly 5-bedroom duplex near parks.",
      "permission": null,
      "authority": "verified",
      "type": "duplex",
      "rent_per_month": 2000,
      "bedroom": 5,
      "bathroom": 4,
      "square_fit": 2600,
      "image": "https://www.christiesresidential.co.uk/wp-content/uploads/2023/09/christies-property-focus-magazine.png"
    },
    {
      "id": 18,
      "description": "Kano, Nigeria - 4-bedroom apartment in a secure complex.",
      "permission": "yes",
      "authority": null,
      "type": "apartment",
      "rent_per_month": 1000,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 2000,
      "image": "https://www.theglobeandmail.com/resizer/v2/Z3GWBU7WYJP33GQU2Q6ASIHIRM.JPG?auth=2d8de47f136ff9aa60101d1c3713043da5727840183d5db1055ae912af444237&width=600&quality=80"
    },
    {
      "id": 19,
      "description": "Houston, US - Modern penthouse in the heart of downtown.",
      "permission": "yes",
      "authority": "verified",
      "type": "penthouse",
      "rent_per_month": 4700,
      "bedroom": 3,
      "bathroom": 2,
      "square_fit": 2300,
      "image": "https://bsmedia.business-standard.com/_media/bs/img/article/2023-04/14/full/1681488257-9461.jpg?im=FeatureCrop,size=(826,465)"
    },
    {
      "id": 20,
      "description": "Edinburgh, UK - Historic building with luxury apartments.",
      "permission": "yes",
      "authority": null,
      "type": "building",
      "rent_per_month": 5200,
      "bedroom": 8,
      "bathroom": 6,
      "square_fit": 4000,
      "image": "https://houseplans.co/media/cached_assets/images/blog_entry/streetscapes_thompson_pano_edited_1_900x600.jpg"
    },
    {
        "id": 21,
        "description": "Sylhet, Bangladesh - 2-bedroom apartment with scenic views.",
        "permission": "yes",
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 300,
        "bedroom": 2,
        "bathroom": 1,
        "square_fit": 800,
        "image": "https://cdn.prod.website-files.com/63eaf818fa58513ec4306b1f/6400475e949248641c6a3a1e_australia-bondi-classic-houses-kate-trifo-6414290.webp"
      },
      {
        "id": 22,
        "description": "Ottawa, Canada - Duplex with open concept living and dining area.",
        "permission": null,
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 2200,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2700,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRves_3PZWKn_vduHE58LczzwCRvdas6DM9-g&s"
      },
      {
        "id": 23,
        "description": "Port Harcourt, Nigeria - Luxurious apartment in a serene environment.",
        "permission": "yes",
        "authority": null,
        "type": "luxury",
        "rent_per_month": 1700,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2500,
        "image": "https://www.your-move.co.uk/property-image/rps_yom-HOO190063/image/HOO190063_20/s.jpg?v=24031"
      },
      {
        "id": 24,
        "description": "Miami, US - Beachfront 3-bedroom penthouse with ocean views.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 6200,
        "bedroom": 3,
        "bathroom": 3,
        "square_fit": 2700,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE3eampwBdDhZnnhM0AfE3Xnt0O0wU6kuKDA&s"
      },
      {
        "id": 25,
        "description": "Glasgow, UK - 4-bedroom building in a prime commercial area.",
        "permission": null,
        "authority": "verified",
        "type": "building",
        "rent_per_month": 7000,
        "bedroom": 6,
        "bathroom": 5,
        "square_fit": 3700,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2lLGt72zAfQ7Y4Rv1HdqhiTNJIn9sks1lJg&s"
      },
      {
        "id": 26,
        "description": "Khulna, Bangladesh - Modern 3-bedroom apartment near the city center.",
        "permission": "yes",
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 400,
        "bedroom": 3,
        "bathroom": 2,
        "square_fit": 1100,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJBaUcnRuIE_FnCq_sAyGyESLZPLuzcJmRRQ&s"
      },
      {
        "id": 27,
        "description": "Quebec City, Canada - Spacious duplex with private backyard.",
        "permission": null,
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 1900,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2400,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLYi4I_9snkmOCDLPzi2NpJSa_JtY9vSP9lg&s"
      },
      {
        "id": 28,
        "description": "Enugu, Nigeria - Newly built 3-bedroom apartment in a quiet neighborhood.",
        "permission": "yes",
        "authority": null,
        "type": "apartment",
        "rent_per_month": 850,
        "bedroom": 3,
        "bathroom": 2,
        "square_fit": 1200,
        "image": "https://cghb.gov.in/Projects/Online-Booking/Godhi-Tamnar-Raigarh-Front-Pic.jpg"
      },
      {
        "id": 29,
        "description": "Chicago, US - Luxury 5-bedroom penthouse in the heart of downtown.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 5400,
        "bedroom": 5,
        "bathroom": 4,
        "square_fit": 3000,
        "image": "https://propertyadviser.in/property-images/s2/mdr-homes-5142-s2.jpg?20092023"
      },
      {
        "id": 30,
        "description": "Liverpool, UK - Modern building with multiple residential units.",
        "permission": null,
        "authority": "verified",
        "type": "building",
        "rent_per_month": 7200,
        "bedroom": 12,
        "bathroom": 10,
        "square_fit": 5000,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrunS6JflztFgv3611orNJcwrVzyfEp-2aFQ&s"
      },
      {
        "id": 31,
        "description": "Barisal, Bangladesh - Affordable 2-bedroom apartment near the river.",
        "permission": "yes",
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 250,
        "bedroom": 2,
        "bathroom": 1,
        "square_fit": 850,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRawhWXf7ye_9TRkztHLZ0H2zPYfOeMbJ9zWw&s"
      },
      {
        "id": 32,
        "description": "Winnipeg, Canada - Family-friendly duplex in a quiet suburb.",
        "permission": null,
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 1600,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2200,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW63unqulPSwc4HpTsfsOpwzORuWFrFVoqCw&s"
      },
      {
        "id": 33,
        "description": "Kano, Nigeria - Luxury apartment with a large terrace.",
        "permission": "yes",
        "authority": "verified",
        "type": "luxury",
        "rent_per_month": 1800,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2300,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShVAcAHVMXYk-pnliwq9CoaZnNaGYpBRWf0g&s"
      },
      {
        "id": 34,
        "description": "Seattle, US - Penthouse with panoramic city views.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 6100,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2600,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgs_s9-a1xjdNh9t9TJSRM8tx4PyKp6oRnGQ&s"
      },
      {
        "id": 35,
        "description": "Oxford, UK - Historic building converted into modern apartments.",
        "permission": null,
        "authority": "verified",
        "type": "building",
        "rent_per_month": 5300,
        "bedroom": 6,
        "bathroom": 5,
        "square_fit": 4200,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU06rKJMhQ5k-F4YQgk2zHQ-hxwtbqPNgl1w&s"
      },
      {
        "id": 36,
        "description": "Mymensingh, Bangladesh - Compact 1-bedroom apartment in a residential area.",
        "permission": "yes",
        "authority": null,
        "type": "apartment",
        "rent_per_month": 200,
        "bedroom": 1,
        "bathroom": 1,
        "square_fit": 700,
        "image": "https://nreig.com/wp-content/uploads/2019/09/Vacant-boarded_shutterstock_1131849035-1024x683.jpg.webp"
      },
      {
        "id": 37,
        "description": "Halifax, Canada - 3-bedroom duplex near the waterfront.",
        "permission": "yes",
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 2100,
        "bedroom": 3,
        "bathroom": 2,
        "square_fit": 1500,
        "image": "https://fortune.com/img-assets/wp-content/uploads/2024/04/GettyImages-1481193734-e1713877260232.jpg?w=1440&q=75"
      },
      {
        "id": 38,
        "description": "Benin City, Nigeria - Contemporary 2-bedroom luxury apartment.",
        "permission": null,
        "authority": "verified",
        "type": "luxury",
        "rent_per_month": 950,
        "bedroom": 2,
        "bathroom": 2,
        "square_fit": 1200,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJk8h2H3ZMTKDhPU3jkYlAgOVJakIvW2BtfA&s"
      },
      {
        "id": 39,
        "description": "Dallas, US - Spacious 4-bedroom duplex in a gated community.",
        "permission": "yes",
        "authority": null,
        "type": "duplex",
        "rent_per_month": 3400,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2400,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrl__CU3Q2RhOpsAZGjwWiEoQdk1jXHPkqzw&s"
      },
      {
        "id": 40,
        "description": "Brighton, UK - Stunning penthouse with sea views.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 4600,
        "bedroom": 3,
        "bathroom": 2,
        "square_fit": 2100,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdT5iOUnG8YIp4_9HFkEJC-q3tYI6NERQjdA&s"
      },
      {
        "id": 41,
        "description": "Comilla, Bangladesh - Newly built 3-bedroom apartment near the market.",
        "permission": "yes",
        "authority": null,
        "type": "apartment",
        "rent_per_month": 350,
        "bedroom": 3,
        "bathroom": 2,
        "square_fit": 1050,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjUoCRJmKywN58vXk_-__AfP314icsGoP1SQ&s"
      },
      {
        "id": 42,
        "description": "Edmonton, Canada - Luxury duplex with modern finishes.",
        "permission": "yes",
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 2400,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2500,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTI3t3oNn6xHV_PhPxDWdEUryUXWUe6XeEHNA&s"
      },
      {
        "id": 43,
        "description": "Ibadan, Nigeria - Affordable 1-bedroom apartment in a secure estate.",
        "permission": "yes",
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 500,
        "bedroom": 1,
        "bathroom": 1,
        "square_fit": 700,
        "image": "https://i0.wp.com/theconstructor.org/wp-content/uploads/2014/10/Residential-building.jpg?resize=450%2C268&ssl=1"
      },
      {
        "id": 44,
        "description": "Boston, US - Modern 2-bedroom apartment with river views.",
        "permission": null,
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 3700,
        "bedroom": 2,
        "bathroom": 2,
        "square_fit": 1300,
        "image": "https://photos.zillowstatic.com/fp/d50c62457d934e26392d431153241f07-p_e.jpg"
      },
      {
        "id": 45,
        "description": "Leeds, UK - Renovated building with multiple luxury units.",
        "permission": "yes",
        "authority": null,
        "type": "building",
        "rent_per_month": 6000,
        "bedroom": 10,
        "bathroom": 8,
        "square_fit": 4300,
        "image": "https://content.knightfrank.com/property/hub2402701/images/cc47633c-fa01-4c9a-8cd5-44314a498b7e-0.jpg?cio=true&h=327"
      },
      {
        "id": 46,
        "description": "Rangpur, Bangladesh - Comfortable 2-bedroom apartment near the park.",
        "permission": "yes",
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 250,
        "bedroom": 2,
        "bathroom": 1,
        "square_fit": 900,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq5ONhGqKQnaLh0jZHVGlVj7pYzmoDTjg73A&s"
      },
      {
        "id": 47,
        "description": "Toronto, Canada - Luxury penthouse in a high-rise building.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 7200,
        "bedroom": 5,
        "bathroom": 4,
        "square_fit": 3200,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZQRkY3x0ne2sopvOp2V1wXwaF5GofG3G-cw&s"
      },
      {
        "id": 48,
        "description": "Abuja, Nigeria - Duplex with private garden and pool.",
        "permission": "yes",
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 3000,
        "bedroom": 4,
        "bathroom": 4,
        "square_fit": 2800,
        "image": "https://img.iproperty.com.my/angel/750x1000-fit/wp-content/uploads/sites/2/2021/08/Purchase-a-landed-property-1024x768.jpg"
      },
      {
        "id": 49,
        "description": "Los Angeles, US - Ultra-modern 6-bedroom luxury penthouse.",
        "permission": "yes",
        "authority": "verified",
        "type": "luxury",
        "rent_per_month": 15000,
        "bedroom": 6,
        "bathroom": 6,
        "square_fit": 4000,
        "image": "https://photos-a.propertyimages.ie/media/2/3/1/4831132/c805c391-877b-42cb-8a85-5dd955dc67cf_l.jpg"
      },
      {
        "id": 50,
        "description": "London, UK - Luxury penthouse with views of the Thames River.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 9000,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2800,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9ppEz89UiRPLQySayDaRgJ4rheHQIdxcESw&s"
      }
    
    
  ]
  
export default PropertyData