const PropertyData = 

[
  {
    "id": 1,
    "description": "New York, USA - Spacious loft in the heart of Manhattan.",
    "permission": "yes",
    "authority": "verified",
    "type": "loft",
    "bedroom": 2,
    "bathroom": 2,
    "square_fit": 2000,
    "imageOne": "https://www.shutterstock.com/image-photo/perfect-neighbourhood-houses-suburb-summer-260nw-1937913955.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH4ndCnhxseSY_Nx49Kgn8DGHGCv5TF0bWtg&s",
    "imageThree":"https://www.wakefit.co/blog/wp-content/uploads/2022/01/Verticle-Drapes-min.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",
    "location": "New York, USA",
    "purpose": "rent",
    "about_property": "This Manhattan loft offers open-plan living with industrial charm. Exposed brick, high ceilings, and oversized windows make this loft perfect for those who appreciate a mix of modern and historical design.",
    "rating": 4.7,
    "price": 7500
  },
  {
    "id": 2,
    "description": "Paris, France - Charming apartment near the Eiffel Tower.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 1500,
    "imageOne": "https://png.pngtree.com/thumb_back/fw800/background/20240614/pngtree-modern-luxurious-real-estate-property-house-background-image_15868464.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqxeZEVnYvXPCJVeKKlf_isnVIbYEkJqIVgA&s",
    "imageThree": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw6llbQsdQnd8T2K9l4LCDWegS4_sLJfipyA&s",
    "imageFour": "https://example.com/images/ny_loft.jpg",   
     "location": "Paris, France",
    "purpose": "sell",
    "about_property": "Located steps away from the Eiffel Tower, this apartment features classic Parisian architecture with modern upgrades. It offers a romantic ambiance with a view of the Paris skyline.",
    "rating": 4.9,
    "price": 1200000
  },
  {
    "id": 3,
    "description": "Tokyo, Japan - Modern condo with city views.",
    "permission": null,
    "authority": null,
    "type": "condo",
    "bedroom": 2,
    "bathroom": 1,
    "square_fit": 1000,
    "imageOne": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjn7mbWlHkzGfpy2lawCw1ugkHUo364wFJNg&s",
    "imageTwo": "https://www.mangoroc.com/wp-content/uploads/2023/08/Taipei-Neihu-furnished-apartment_living-room-view-4-818x540.webp",
    "imageThree": "https://www.mydomaine.com/thmb/D9NOmUiBWEmG_XaYUTDn_t6OAms=/872x0/filters:no_upscale():strip_icc()/midcentury-modern-apartment-decor-ideas-3-katie-hodges-midwilshire-2-5c414802e6d148dbb27f302078dd555f.png",
    "imageFour": "https://example.com/images/ny_loft.jpg",
    "location": "Tokyo, Japan",
    "purpose": "rent",
    "about_property": "This contemporary condo in Tokyo offers minimalist design and breathtaking city views. Perfect for professionals looking for a sleek, modern living space in the center of Tokyo.",
    "rating": 4.6,
    "price": 6000
  },
  {
    "id": 4,
    "description": "Sydney, Australia - Beachfront villa with stunning ocean views.",
    "permission": "yes",
    "authority": "verified",
    "type": "villa",
    "bedroom": 5,
    "bathroom": 4,
    "square_fit": 3500,
    "imageOne": "https://cdn.pixabay.com/photo/2017/07/17/00/54/house-2511060_640.jpg",
    "imageTwo": "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2022/03/New-York-apartment-style-1.jpeg?width=900",
    "imageThree": "https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2017/9/13/0/CI_MeganTaylor_FramedWallpaper_StatementWallpapers.jpg.rend.hgtvcom.1280.960.suffix/1505262100919.jpeg",
    "imageFour": "https://example.com/images/ny_loft.jpg",
    "location": "Sydney, Australia",
    "purpose": "sell",
    "about_property": "This luxurious beachfront villa boasts expansive ocean views, private access to the beach, and modern amenities for a lavish coastal lifestyle. An entertainer's dream with large outdoor living spaces.",
    "rating": 4.9,
    "price": 4500000
  },
  {
    "id": 5,
    "description": "Berlin, Germany - Contemporary penthouse with rooftop terrace.",
    "permission": null,
    "authority": null,
    "type": "penthouse",
    "bedroom": 4,
    "bathroom": 3,
    "square_fit": 2800,
    "imageOne": "https://thumbor.forbes.com/thumbor/fit-in/x/https://www.forbes.com/advisor/wp-content/uploads/2021/08/download-7.jpg",
    "imageTwo": "https://www.ikea.com/ext/ingkadam/m/55e30d69cef5c521/original/PH199004.jpg?f=s",
    "imageThree": "https://thumbs.dreamstime.com/b/modern-living-room-19483224.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",
    "location": "Berlin, Germany",
    "purpose": "rent",
    "about_property": "This stunning Berlin penthouse features sleek modern design, an expansive rooftop terrace, and views of the city skyline. The perfect combination of luxury and modern city living.",
    "rating": 4.8,
    "price": 11000
  },
  {
    "id": 6,
    "description": "Dubai, UAE - Extravagant apartment with views of the Burj Khalifa.",
    "permission": "yes",
    "authority": null,
    "type": "apartment",
    "bedroom": 3,
    "bathroom": 3,
    "square_fit": 2200,
    "imageOne": "https://media.istockphoto.com/id/1165384568/photo/europe-modern-complex-of-residential-buildings.jpg?s=612x612&w=0&k=20&c=iW4NBiMPKEuvaA7h8wIsPHikhS64eR-5EVPfjQ9GPOA=",
    "imageTwo": "https://www.thespruce.com/thmb/INR4W-MKxwudzUFROUawQ0kCE5c=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/thespruce-smalllivingroom-arborandco-854e4a16894445eebb798f065aec1137.png",
    "imageThree": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCjAo5lAeKqT5FeTeVvOPJpPow75Cfj0aEOg&s",
    "imageFour": "https://example.com/images/ny_loft.jpg",
    "location": "Dubai, UAE",
    "purpose": "sell",
    "about_property": "This upscale apartment offers unparalleled views of the Burj Khalifa and luxurious amenities, including a private pool and concierge service. A truly iconic residence in the heart of Dubai.",
    "rating": 4.9,
    "price": 2500000
  },
  {
    "id": 7,
    "description": "Barcelona, Spain - Penthouse with a private rooftop pool.",
    "permission": "yes",
    "authority": "verified",
    "type": "penthouse",
    "bedroom": 4,
    "bathroom": 3,
    "square_fit": 2700,
    "imageOne": "https://www.shutterstock.com/image-photo/new-modern-block-flats-green-260nw-2461488711.jpg",
    "imageTwo": "https://hips.hearstapps.com/hmg-prod/images/curated-nest-6530345bd3390.jpg",
    "imageThree": "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2024/02/Luxe-NYC-apartment-interior-by-Decorilla-1024x574.jpg?width=900",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Barcelona, Spain",
    "purpose": "rent",
    "about_property": "This Barcelona penthouse offers a private rooftop pool, large terraces, and spacious living areas with panoramic views of the city. Perfect for enjoying the Mediterranean lifestyle.",
    "rating": 4.7,
    "price": 14000
  },
  {
    "id": 8,
    "description": "Miami, USA - Luxury condo with beachfront access.",
    "permission": "yes",
    "authority": null,
    "type": "condo",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 2100,
    "imageOne": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQf9FXwoX6TFCR6w5JFAk5PELHZhBAYUIqfg&s",
    "imageTwo": "https://www.bocadolobo.com/en/inspiration-and-ideas/wp-content/uploads/2023/05/Luxurious-Apartment-Interior-Design-by-Aya-Al-Ansari-in-Egypt-4.jpg",
    "imageThree": "https://thumbor.forbes.com/thumbor/fit-in/900x510/https://www.forbes.com/home-improvement/wp-content/uploads/2023/02/image6.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Miami, USA",
    "purpose": "sell",
    "about_property": "This elegant beachfront condo offers direct access to Miami's iconic beaches, sleek interiors, and world-class amenities. An exceptional residence for those seeking luxury in South Florida.",
    "rating": 4.8,
    "price": 3200000
  },
  {
    "id": 9,
    "description": "Rome, Italy - Historic apartment in the city center.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 2,
    "bathroom": 2,
    "square_fit": 1800,
    "imageOne": "https://media.istockphoto.com/id/532344368/photo/new-white-apartment-houses.jpg?s=612x612&w=0&k=20&c=SkOVEab-VOMN6NdZfAsxJra3JKMGAVpC2P3OK1ujp5k=",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm0JYxjtsBpqKi08zstdAmDlhFgd7TQiInCg&s",
    "imageThree": "https://i0.wp.com/cocolapinedesign.com/wp-content/uploads/A-beige-bedroom-and-warm-decor-in-a-historic-Swedish-apartment2.jpg?resize=1140%2C760&ssl=1",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Rome, Italy",
    "purpose": "rent",
    "about_property": "This historic apartment is located in the heart of Rome, blending classic Roman architecture with modern interiors. A perfect home for experiencing the beauty of Rome.",
    "rating": 4.6,
    "price": 5000
  },
  {
    "id": 10,
    "description": "Los Angeles, USA - Hillside villa with stunning city views.",
    "permission": "yes",
    "authority": null,
    "type": "villa",
    "bedroom": 5,
    "bathroom": 4,
    "square_fit": 3200,
    "imageOne": "https://media.istockphoto.com/id/507488437/photo/modern-architecture-in-berlin-germany.jpg?s=612x612&w=is&k=20&c=a9TEnz_vb59zB_NmJLLKAWcTZe-lnx4DwUFoxQ0ADY4=",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6PTfmReBJSlE5tozKsbZX2SGEZhVN8PF19A&s",
    "imageThree": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrqfnxqUc5gbsmtYjieN0AV6usMK8SWYFS0Q&s",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Los Angeles, USA",
    "purpose": "sell",
    "about_property": "Located in the hills of Los Angeles, this luxurious villa features spacious living areas, a private pool, and sweeping views of the city. Ideal for those seeking privacy and luxury.",
    "rating": 4.9,
    "price": 3800000
  },
  {
    "id": 11,
    "description": "London, UK - Luxury penthouse with views of the Thames River.",
    "permission": "yes",
    "authority": null,
    "type": "penthouse",
    "bedroom": 4,
    "bathroom": 3,
    "square_fit": 2800,
    "imageOne": "https://media.istockphoto.com/id/636865286/photo/apartment-houses.jpg?s=612x612&w=0&k=20&c=iDBX47pbbc4YFE28tiEL39zdsTJZr2kMctbW5H1qx_k=",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbmHpEqOpmly7WwXvVTD3AslKW-PW_5kvSYA&s",
    "imageThree": "https://cdn.mos.cms.futurecdn.net/fvshRaCyyYAxHDxgppfHWH-320-80.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "London, UK",
    "purpose": "rent",
    "about_property": "This luxury penthouse offers breathtaking views of the Thames River, modern interior design, high-end appliances, and spacious living areas. Perfect for families or professionals seeking a stylish and convenient location in the heart of London.",
    "rating": 4.8,
    "price": 9000
  },
  {
    "id": 12,
    "description": "Amsterdam, Netherlands - Canal-side apartment with scenic views.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 1700,
    "imageOne": "https://www.shutterstock.com/image-photo/modern-apartment-middel-town-quite-260nw-1718630734.jpg",
    "imageTwo": "https://hips.hearstapps.com/hmg-prod/images/small-living-room-4-1578520528.jpg",
    "imageThree": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTj3_Krp-guqTPf7kSd293jhrmY6dl551UZQVJENkD4l8U6aSI7m1X3WgzQJawfe302Y6s&usqp=CAU",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Amsterdam, Netherlands",
    "purpose": "rent",
    "about_property": "This beautiful canal-side apartment features large windows with breathtaking views of Amsterdam’s iconic canals. The property boasts a spacious living area with modern interiors and wooden floors.",
    "rating": 4.7,
    "price": 6500
  },
  {
    "id": 13,
    "description": "Zurich, Switzerland - Modern villa with mountain views.",
    "permission": null,
    "authority": "verified",
    "type": "villa",
    "bedroom": 4,
    "bathroom": 4,
    "square_fit": 3000,
    "imageOne": "https://media.istockphoto.com/id/175767618/photo/modern-townhouse-complex.jpg?s=612x612&w=0&k=20&c=ltPDM5QTC1a4cdr7Fjvct-KNlNCUPC_IyNC2f93eJ84=",
    "imageTwo": "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,w_730/at%2Fhouse%20tours%2F2023-House-Tours%2F2023-February%2FCaroline-M%2Ftours-jerseycity-caroline-m-05",
    "imageThree": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAxc9mqknRO3SIbxleI4p7RP7hteqkpfn3nA&s",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Zurich, Switzerland",
    "purpose": "sell",
    "about_property": "This stunning villa offers panoramic views of the Swiss Alps, state-of-the-art amenities, and contemporary design. Situated in the peaceful outskirts of Zurich, it offers both privacy and luxury.",
    "rating": 4.9,
    "price": 4200000
  },
  {
    "id": 14,
    "description": "Lisbon, Portugal - Historic townhouse in the Alfama district.",
    "permission": "yes",
    "authority": "verified",
    "type": "townhouse",
    "bedroom": 3,
    "bathroom": 3,
    "square_fit": 1800,
    "imageOne": "https://thumbs.dreamstime.com/b/nice-comfortable-neighborhood-townhouses-suburbs-canada-booming-real-estate-130172724.jpg",
    "imageTwo": "https://cdn.mos.cms.futurecdn.net/jBRawEqTNfC6sa7V9b9vxg-320-80.png",
    "imageThree": "https://cdn.prod.website-files.com/62bc621399f5713af580f208/65fde7c24f4976e5ab116bf2_Ori%20Apartments%20Tampa.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Lisbon, Portugal",
    "purpose": "rent",
    "about_property": "This beautiful historic townhouse in the Alfama district has been fully renovated to include modern comforts while retaining its old-world charm. The property features a rooftop terrace with stunning views of the city.",
    "rating": 4.8,
    "price": 4500
  },
  {
    "id": 15,
    "description": "Melbourne, Australia - Penthouse apartment with bay views.",
    "permission": "yes",
    "authority": null,
    "type": "penthouse",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 2500,
    "imageOne": "https://www.shutterstock.com/image-photo/houston-tx-usa-3222023-portrait-260nw-2511701521.jpg",
    "imageTwo": "https://images.squarespace-cdn.com/content/v1/603bc169543f684c561a2891/855dcacd-2f8f-4987-b611-64691c3523fa/small+apartment+living+room+and+work+area",
    "imageThree": "https://www.realsimple.com/thmb/7CJUmKCNNxVrkC3V2kgSP-f52ts=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/CopyofCopyofwaikikiairbnb-2224-12e79be795b04ae6a3c0763823096a12.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Melbourne, Australia",
    "purpose": "sell",
    "about_property": "This luxurious penthouse offers sweeping views of Port Phillip Bay. The residence is designed with elegance and modernity in mind, featuring high-end finishes, a rooftop garden, and a private elevator.",
    "rating": 4.9,
    "price": 2700000
  },
  {
    "id": 16,
    "description": "Cape Town, South Africa - Coastal villa with breathtaking ocean views.",
    "permission": "yes",
    "authority": "verified",
    "type": "villa",
    "bedroom": 5,
    "bathroom": 5,
    "square_fit": 4000,
    "imageOne": "https://www.shutterstock.com/image-photo/houston-tx-usa-3222023-portrait-260nw-2511701521.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-pKnhCsR-DcgXwrIqe9OzOgdgwHx-blUGMA&s",
    "imageThree": "https://nextluxury.com/wp-content/uploads/cute-apartment-living-room-ideas-tiffanyjanellcreativestudio.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Cape Town, South Africa",
    "purpose": "rent",
    "about_property": "This stunning villa is perched on a cliffside with uninterrupted views of the Atlantic Ocean. It offers expansive indoor and outdoor living spaces, including a private pool and terrace.",
    "rating": 5.0,
    "price": 15000
  },
  {
    "id": 17,
    "description": "Hong Kong - High-rise apartment with city skyline views.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 2,
    "bathroom": 2,
    "square_fit": 1300,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz_TTgtHLVFCqGQkb1vINWWikrsm3Up7VVcQ&s",
    "imageThree": "https://www.home-designing.com/wp-content/uploads/2018/04/large-wall-clock.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Hong Kong",
    "purpose": "rent",
    "about_property": "This modern high-rise apartment offers sweeping views of the Hong Kong skyline and Victoria Harbour. It features sleek interiors with top-quality finishes, ideal for urban professionals.",
    "rating": 4.7,
    "price": 9000
  },
  {
    "id": 18,
    "description": "Madrid, Spain - Elegant villa with private garden.",
    "permission": "yes",
    "authority": "verified",
    "type": "villa",
    "bedroom": 6,
    "bathroom": 5,
    "square_fit": 5000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPTo3tYqbqSogYPQmtBLxLMkVTu9oUQlWqEQ&s",
    "imageThree": "https://cdn.shopify.com/s/files/1/1144/9038/files/living_room_with_green_couch.jpg?v=1659133195",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Madrid, Spain",
    "purpose": "sell",
    "about_property": "Located in one of Madrid’s most prestigious neighborhoods, this villa offers a private garden, luxurious interior spaces, and a large swimming pool. It combines modern design with traditional Spanish charm.",
    "rating": 4.9,
    "price": 4900000
  },
  {
    "id": 19,
    "description": "San Francisco, USA - Victorian-style home in Pacific Heights.",
    "permission": "yes",
    "authority": "verified",
    "type": "house",
    "bedroom": 4,
    "bathroom": 3,
    "square_fit": 3000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBQP1fxJaz_9SZYb5rf_O1alXKwMdpCxlH9A&s",
    "imageThree": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWHaf9S9-51WNQyrJh_K7vVZyXyoYvKLQyNQ&s",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "San Francisco, USA",
    "purpose": "rent",
    "about_property": "This historic Victorian home is located in the Pacific Heights neighborhood. It features beautifully restored period details, combined with modern upgrades. The house includes a large backyard and a spacious garage.",
    "rating": 4.8,
    "price": 12500
  },
  {
    "id": 20,
    "description": "Dubai, UAE - Luxury villa with private beach access.",
    "permission": null,
    "authority": "verified",
    "type": "villa",
    "bedroom": 6,
    "bathroom": 6,
    "square_fit": 7000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://hips.hearstapps.com/hmg-prod/images/ahp-230508-01-fs-1-652db069ca3c2.jpg",
    "imageThree": "https://media.istockphoto.com/id/1333060261/photo/modern-living-room-interior-design.jpg?s=612x612&w=0&k=20&c=4P4Ke-N4n8wk4xOpwCVw5HGwFVFi5GEOavQSaepbKOE=",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Dubai, UAE",
    "purpose": "sell",
    "about_property": "This exclusive villa offers direct access to a private beach, spacious living areas, a state-of-the-art kitchen, and a rooftop terrace with stunning views of the Dubai skyline and sea.",
    "rating": 5.0,
    "price": 7000000
  },
  {
    "id": 21,
    "description": "Singapore - Modern apartment with Marina Bay views.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 2000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSex38qvF10TxCorBJaAFLYo8TDBhl5GwQojw&s",
    "imageThree": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSviAtLTCE1HQfjGIOpV1HcCOsvOCUN4Thddw&s",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Singapore",
    "purpose": "rent",
    "about_property": "This modern apartment in Singapore offers luxury living with direct views of Marina Bay. The property features large windows, sleek interior finishes, and a spacious open-plan layout.",
    "rating": 4.8,
    "price": 8500
  },
  {
    "id": 22,
    "description": "Vienna, Austria - Penthouse with views of the Vienna Opera House.",
    "permission": "yes",
    "authority": null,
    "type": "penthouse",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 2500,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY0ikm_bCJrmhlI262zCB75KI5LH0IynoWdw&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Vienna, Austria",
    "purpose": "sell",
    "about_property": "This stunning penthouse offers views of the Vienna Opera House and combines modern design with traditional Viennese architectural elements. It includes a large terrace perfect for entertaining.",
    "rating": 4.9,
    "price": 3200000
  },
  {
    "id": 23,
    "description": "Los Angeles, USA - Ultra-modern home in Beverly Hills.",
    "permission": null,
    "authority": "verified",
    "type": "house",
    "bedroom": 5,
    "bathroom": 5,
    "square_fit": 6000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://s3-ap-southeast-1.amazonaws.com/atap-main/gallery-full/7c4a8bdd-5a45-44f1-bc0b-666ff60c1db4/modern-apartment-design.jpg",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Los Angeles, USA",
    "purpose": "sell",
    "about_property": "This ultra-modern home features cutting-edge design and technology, including smart home systems, a home theater, and an infinity pool overlooking Beverly Hills. Ideal for luxury living.",
    "rating": 5.0,
    "price": 12000000
  },
  {
    "id": 24,
    "description": "Toronto, Canada - Spacious condo in the downtown core.",
    "permission": "yes",
    "authority": "verified",
    "type": "condo",
    "bedroom": 2,
    "bathroom": 2,
    "square_fit": 1400,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://i0.wp.com/cocolapinedesign.com/wp-content/uploads/MED2BC6DD98D06142F5BC5DFCC62072406A_20200204102130_w2200_q90.jpg?resize=1024%2C683&ssl=1",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Toronto, Canada",
    "purpose": "rent",
    "about_property": "This modern condo offers spacious living in the heart of downtown Toronto. With views of the CN Tower, the condo features top-quality finishes and excellent building amenities, including a gym and pool.",
    "rating": 4.7,
    "price": 4000
  },
  {
    "id": 25,
    "description": "Bangkok, Thailand - Modern condo with city skyline views.",
    "permission": "yes",
    "authority": "verified",
    "type": "condo",
    "bedroom": 2,
    "bathroom": 2,
    "square_fit": 1200,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToVE0g81iqywyGgS-4ew0HgzDq2-YhOOQPWg&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Bangkok, Thailand",
    "purpose": "rent",
    "about_property": "This stylish condo in Bangkok offers breathtaking views of the city skyline. It features a contemporary design with high-quality finishes, and the building includes amenities such as a swimming pool and fitness center.",
    "rating": 4.8,
    "price": 3500
  },
  {
    "id": 26,
    "description": "Rome, Italy - Historic apartment in the heart of the city.",
    "permission": "yes",
    "authority": null,
    "type": "apartment",
    "bedroom": 2,
    "bathroom": 1,
    "square_fit": 1000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://nextluxury.com/wp-content/uploads/apartment-small-living-room-ideas-1.jpg",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Rome, Italy",
    "purpose": "rent",
    "about_property": "This charming apartment is located in the heart of Rome, just steps away from iconic landmarks. It has been beautifully restored, featuring original frescoes and a cozy balcony with city views.",
    "rating": 4.9,
    "price": 5000
  },
  {
    "id": 27,
    "description": "Barcelona, Spain - Beachfront villa with private pool.",
    "permission": "yes",
    "authority": "verified",
    "type": "villa",
    "bedroom": 5,
    "bathroom": 4,
    "square_fit": 4000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://cdn.decoist.com/wp-content/uploads/2018/06/Ergonomic-and-appealing-small-apartment-living-room-with-ample-shelf-space.jpg",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Barcelona, Spain",
    "purpose": "sell",
    "about_property": "This luxurious beachfront villa in Barcelona offers stunning ocean views and direct beach access. The property features a private pool, spacious living areas, and beautifully landscaped gardens.",
    "rating": 5.0,
    "price": 3200000
  },
  {
    "id": 28,
    "description": "Dubai, UAE - Luxury apartment in a high-rise tower.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 3,
    "bathroom": 3,
    "square_fit": 2500,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://nextluxury.com/wp-content/uploads/apartment-small-living-room-ideas-1.jpg",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Dubai, UAE",
    "purpose": "rent",
    "about_property": "This luxurious apartment offers stunning views of the Burj Khalifa and Dubai Fountain. With high-end finishes and top-notch amenities, this property is perfect for those seeking a lavish lifestyle.",
    "rating": 4.9,
    "price": 10000
  },
  {
    "id": 29,
    "description": "Toronto, Canada - Elegant house in a quiet neighborhood.",
    "permission": "yes",
    "authority": "verified",
    "type": "house",
    "bedroom": 4,
    "bathroom": 3,
    "square_fit": 3000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPY3hYppM34Xj6Ypzv6VT8QFXt3RHfrW-uKg&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Toronto, Canada",
    "purpose": "sell",
    "about_property": "This elegant family home is situated in a quiet neighborhood of Toronto. It features spacious rooms, a beautifully landscaped backyard, and is close to schools and parks, making it perfect for families.",
    "rating": 4.8,
    "price": 1500000
  },
  {
    "id": 30,
    "description": "Seattle, USA - Contemporary home with waterfront access.",
    "permission": "yes",
    "authority": "verified",
    "type": "house",
    "bedroom": 5,
    "bathroom": 4,
    "square_fit": 4000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhS7K21hX5RNVsDH8hONLK9o_PtPgUfwBPMA&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Seattle, USA",
    "purpose": "sell",
    "about_property": "This contemporary waterfront home features stunning views of Puget Sound and the Olympic Mountains. With modern design elements and luxurious finishes, it includes a private dock and spacious outdoor areas.",
    "rating": 4.9,
    "price": 3500000
  },
  {
    "id": 31,
    "description": "Berlin, Germany - Modern loft in a trendy neighborhood.",
    "permission": "yes",
    "authority": "verified",
    "type": "loft",
    "bedroom": 2,
    "bathroom": 2,
    "square_fit": 1800,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLhXWRuoq3qb7T0meRvBL10h6rFDQVcDhF-Q&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Berlin, Germany",
    "purpose": "rent",
    "about_property": "This stylish loft in Berlin is located in a trendy neighborhood known for its vibrant culture. It features high ceilings, large windows, and an open-plan design, perfect for modern urban living.",
    "rating": 4.8,
    "price": 4500
  },
  {
    "id": 32,
    "description": "Singapore - Luxury penthouse with skyline views.",
    "permission": null,
    "authority": null,
    "type": "penthouse",
    "bedroom": 4,
    "bathroom": 4,
    "square_fit": 3500,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6DzGnDKZ6CuWIX-jsTj2L8dr4gZRsxg9ruQ&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Singapore",
    "purpose": "sell",
    "about_property": "This exquisite penthouse in Singapore offers breathtaking skyline views and luxury finishes. It features a private terrace, spacious living areas, and access to high-end amenities within the building.",
    "rating": 4.9,
    "price": 6000000
  },
  {
    "id": 33,
    "description": "Copenhagen, Denmark - Cozy apartment with a garden.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 2,
    "bathroom": 1,
    "square_fit": 1300,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://as2.ftcdn.net/v2/jpg/05/56/08/11/1000_F_556081113_0Z65rqTLaaboAs5rCcxFP3pw5O5xU1dg.jpg",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    "location": "Copenhagen, Denmark",
    "purpose": "rent",
    "about_property": "This cozy apartment features a private garden, perfect for enjoying the Danish summer. Located in a vibrant neighborhood, it offers modern amenities and a welcoming atmosphere.",
    "rating": 4.7,
    "price": 3000
  },
  {
    "id": 34,
    "description": "Stockholm, Sweden - Modern home near the waterfront.",
    "permission": "yes",
    "authority": "verified",
    "type": "house",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 2200,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXyYWZIV12XIaU59ysU4kJFo-lHjYF47FNIg&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    "location": "Stockholm, Sweden",
    "purpose": "sell",
    "about_property": "This modern home is situated near the waterfront in Stockholm, featuring sleek designs and sustainable features. The property has easy access to public transport and local amenities.",
    "rating": 4.8,
    "price": 1600000
  },
  {
    "id": 35,
    "description": "Brisbane, Australia - Spacious family home in a quiet suburb.",
    "permission": null,
    "authority": "verified",
    "type": "house",
    "bedroom": 5,
    "bathroom": 3,
    "square_fit": 3500,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLHMreRbUZ4oHnaC_SOlzT2UEtzLZ4PNInuw&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Brisbane, Australia",
    "purpose": "rent",
    "about_property": "This spacious family home offers a large backyard and plenty of living space. Located in a quiet suburb of Brisbane, it is perfect for families looking for comfort and convenience.",
    "rating": 4.7,
    "price": 4200
  },
  {
    "id": 36,
    "description": "Amsterdam, Netherlands - Luxury canal house.",
    "permission": "yes",
    "authority": null,
    "type": "house",
    "bedroom": 4,
    "bathroom": 3,
    "square_fit": 3200,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://media.designcafe.com/wp-content/uploads/2021/11/08175125/cozy-apartment-living-room.jpg",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Amsterdam, Netherlands",
    "purpose": "sell",
    "about_property": "This luxurious canal house in Amsterdam combines historic charm with modern comforts. It features spacious living areas, a beautiful garden, and direct access to the canals.",
    "rating": 4.9,
    "price": 3000000
  },
  {
    "id": 37,
    "description": "Madrid, Spain - Penthouse with terrace in the city center.",
    "permission": "yes",
    "authority": "verified",
    "type": "penthouse",
    "bedroom": 2,
    "bathroom": 2,
    "square_fit": 1500,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://cdn.mos.cms.futurecdn.net/o8ydPcPiMceFGjBSsMW7zG-1200-80.png",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Madrid, Spain",
    "purpose": "rent",
    "about_property": "This stylish penthouse offers a spacious terrace with stunning views of the Madrid skyline. It is located in the heart of the city, providing easy access to shops and restaurants.",
    "rating": 4.8,
    "price": 3500
  },
  {
    "id": 38,
    "description": "Lisbon, Portugal - Modern apartment with historic charm.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 1800,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://cdn.onekindesign.com/wp-content/uploads/2015/04/Cozy-Living-Room-Designs-04-1-Kindesign.jpg",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Lisbon, Portugal",
    "purpose": "sell",
    "about_property": "This modern apartment combines contemporary design with historic charm, featuring beautiful tiles and high ceilings. Located in the heart of Lisbon, it is close to local attractions.",
    "rating": 4.7,
    "price": 750000
  },
  {
    "id": 39,
    "description": "Oslo, Norway - Stylish apartment with fjord views.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 2,
    "bathroom": 1,
    "square_fit": 1200,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdriQfXd-2SGf4b-PNH1YO8ixnYDGRNQZlyA&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Oslo, Norway",
    "purpose": "rent",
    "about_property": "This stylish apartment in Oslo offers stunning views of the fjord. With modern amenities and an open floor plan, it provides a comfortable living experience in a vibrant neighborhood.",
    "rating": 4.8,
    "price": 4000
  },
  {
    "id": 40,
    "description": "Vienna, Austria - Elegant historic apartment.",
    "permission": null,
    "authority": null,
    "type": "apartment",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 1500,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRISea1gHn9td1TsX6k63EuuzGVb8s7DR5k-Q&s",
    "imageThree": "https://s3-ap-southeast-1.amazonaws.com/atap-main/gallery-full/7c4a8bdd-5a45-44f1-bc0b-666ff60c1db4/modern-apartment-design.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Vienna, Austria",
    "purpose": "sell",
    "about_property": "This elegant historic apartment in Vienna features classic architecture and modern amenities. It is located in a cultural district, surrounded by museums, cafes, and parks.",
    "rating": 4.9,
    "price": 1200000
  },
  {
    "id": 41,
    "description": "Helsinki, Finland - Cozy cottage by the lake.",
    "permission": "yes",
    "authority": "verified",
    "type": "cottage",
    "bedroom": 3,
    "bathroom": 1,
    "square_fit": 1500,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://static.vecteezy.com/system/resources/previews/023/122/003/non_2x/modern-interior-design-of-cozy-apartment-living-room-with-sofa-ai-generated-photo.jpeg",
    "imageThree": "https://cdn.apartmenttherapy.info/image/upload/v1696468267/at/SEO%20Updates/modern-living-room-ideas/patterns-modern-living-room.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Helsinki, Finland",
    "purpose": "rent",
    "about_property": "This cozy cottage by the lake offers a serene retreat with beautiful nature views. It is perfect for those looking to escape the city and enjoy outdoor activities.",
    "rating": 4.7,
    "price": 2500
  },
  {
    "id": 42,
    "description": "Budapest, Hungary - Stylish apartment in a historic building.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 2,
    "bathroom": 1,
    "square_fit": 1100,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://hips.hearstapps.com/hmg-prod/images/chicinteriors08262020-17242web-65303a490ade8.jpg?crop=1xw:0.9499417927823051xh;center,top&resize=980:*",
    "imageThree": "https://cdn.decoist.com/wp-content/uploads/2018/06/Scandinavian-style-is-perfect-for-the-small-apartment-living-room.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Budapest, Hungary",
    "purpose": "sell",
    "about_property": "This stylish apartment is located in a historic building in Budapest, featuring modern amenities and traditional architecture. It is conveniently located near public transport and local attractions.",
    "rating": 4.8,
    "price": 450000
  },
  {
    "id": 43,
    "description": "Kuala Lumpur, Malaysia - Modern high-rise apartment.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 1600,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkbBCnMg4S3WTGYksOimH50aQKKpos5HUe8Q&s",
    "imageThree": "https://decoholic.org/wp-content/uploads/2022/05/small-apartment-living-room-mirror-idea.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Kuala Lumpur, Malaysia",
    "purpose": "rent",
    "about_property": "This modern high-rise apartment in Kuala Lumpur offers stunning city views and convenient access to shopping and dining. It features contemporary design and excellent building amenities.",
    "rating": 4.8,
    "price": 3000
  },
  {
    "id": 44,
    "description": "Auckland, New Zealand - Spacious family home in a suburban area.",
    "permission": null,
    "authority": null,
    "type": "house",
    "bedroom": 4,
    "bathroom": 3,
    "square_fit": 3200,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvpV-yspGMxxQ2H1SuFbGfyrYrRGWBPOtZSA&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Auckland, New Zealand",
    "purpose": "sell",
    "about_property": "This spacious family home in Auckland features a large backyard and modern living spaces. It is located in a friendly suburban area, ideal for families looking for comfort and community.",
    "rating": 4.7,
    "price": 1200000
  },
  {
    "id": 45,
    "description": "Cape Town, South Africa - Luxury apartment with mountain views.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 2000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://hips.hearstapps.com/hmg-prod/images/fl-youngh-philly-livingr2-129146-55mv2-1637083434.png?crop=1xw:0.8102493074792244xh;center,top&resize=1200:*",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Cape Town, South Africa",
    "purpose": "rent",
    "about_property": "This luxurious apartment in Cape Town offers stunning views of Table Mountain. It features modern interiors, a spacious layout, and access to exclusive building amenities.",
    "rating": 4.9,
    "price": 4500
  },
  {
    "id": 46,
    "description": "Rio de Janeiro, Brazil - Beachfront property with stunning views.",
    "permission": "yes",
    "authority": "verified",
    "type": "villa",
    "bedroom": 5,
    "bathroom": 4,
    "square_fit": 5000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://www.designideasguide.com/wp-content/uploads/2022/04/Masculine-Mens-Living-Room-Decor-Ideas.jpg.webp",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Rio de Janeiro, Brazil",
    "purpose": "sell",
    "about_property": "This stunning beachfront villa in Rio de Janeiro offers unparalleled views of the ocean and surrounding mountains. With luxury finishes and outdoor living spaces, it is perfect for relaxation and entertainment.",
    "rating": 5.0,
    "price": 4000000
  },
  {
    "id": 47,
    "description": "Mexico City, Mexico - Modern apartment in a vibrant neighborhood.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 2,
    "bathroom": 2,
    "square_fit": 1500,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://www.bhg.com/thmb/dgy0b4w_W0oUJUxc7M4w3H4AyDo=/1866x0/filters:no_upscale():strip_icc()/living-room-gallery-shelves-l-shaped-couch-ELeyNpyyqpZ8hosOG3EG1X-b5a39646574544e8a75f2961332cd89a.jpg",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Mexico City, Mexico",
    "purpose": "rent",
    "about_property": "This modern apartment in Mexico City is located in a vibrant neighborhood filled with shops and restaurants. It features stylish interiors and excellent building amenities, including a gym.",
    "rating": 4.7,
    "price": 2800
  },
  {
    "id": 48,
    "description": "San Francisco, USA - Iconic Victorian house.",
    "permission": "yes",
    "authority": "verified",
    "type": "house",
    "bedroom": 4,
    "bathroom": 3,
    "square_fit": 2500,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://www.thespruce.com/thmb/S8tYKXzFhGjDB_X6BHXZyPMhejs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/rsw2320h1548-aafef038b55e4ca5ac3f2ed49337971a.jpeg",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    "location": "San Francisco, USA",
    "purpose": "sell",
    "about_property": "This iconic Victorian house in San Francisco features stunning architecture and modern updates. Located in a prime neighborhood, it is close to parks, restaurants, and public transport.",
    "rating": 4.8,
    "price": 2200000
  },
  {
    "id": 49,
    "description": "Lisbon, Portugal - Contemporary townhouse in a historical district.",
    "permission": "yes",
    "authority": "verified",
    "type": "townhouse",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 1800,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBlqUjrsqrprrBhIbmFiXT_g_JZGMDe8fskA&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Lisbon, Portugal",
    "purpose": "rent",
    "about_property": "This contemporary townhouse in Lisbon features modern amenities while preserving historical charm. Located in a vibrant district, it is perfect for those looking to experience the city.",
    "rating": 4.6,
    "price": 3000
  },
  {
    "id": 50,
    "description": "Bangkok, Thailand - Luxurious penthouse in a prime location.",
    "permission": "yes",
    "authority": "verified",
    "type": "penthouse",
    "bedroom": 4,
    "bathroom": 3,
    "square_fit": 3200,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAd2VOnEoja6XgxMBcpWLCXiPIchDw5u_-lg&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Bangkok, Thailand",
    "purpose": "sell",
    "about_property": "This luxurious penthouse in Bangkok offers stunning city views and high-end finishes. It features spacious living areas and top-notch amenities, making it perfect for luxurious urban living.",
    "rating": 4.9,
    "price": 3500000
  },
  {
    "id": 51,
    "description": "Dubai, UAE - Spacious villa with private pool.",
    "permission": null,
    "authority": "verified",
    "type": "villa",
    "bedroom": 5,
    "bathroom": 6,
    "square_fit": 6000,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://image1.rugs-direct.com/rug_gallery/cms2/chic-and-verstaile-apartment-living-room-ideas.jpeg",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Dubai, UAE",
    "purpose": "rent",
    "about_property": "This spacious villa in Dubai features a private pool and luxurious living spaces. It is located in a premium community with access to world-class amenities.",
    "rating": 4.9,
    "price": 7500
  },
  {
    "id": 52,
    "description": "Berlin, Germany - Trendy loft in a central location.",
    "permission": "yes",
    "authority": null,
    "type": "loft",
    "bedroom": 1,
    "bathroom": 1,
    "square_fit": 1100,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTamDm2hEPbFP0mCNfbzP_LVdd6nMAZXNcjQA&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Berlin, Germany",
    "purpose": "sell",
    "about_property": "This trendy loft in Berlin is located in a central area, offering modern design and ample natural light. It is perfect for young professionals looking for style and convenience.",
    "rating": 4.7,
    "price": 500000
  },
  {
    "id": 53,
    "description": "Tokyo, Japan - Stylish modern apartment in a vibrant district.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 2,
    "bathroom": 1,
    "square_fit": 1200,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://hips.hearstapps.com/hmg-prod/images/designed-by-arlyn-hernandez-photo-by-sara-ligorria-tramp-5-652db3f539ed5.jpg?crop=0.710xw:1.00xh;0.280xw,0&resize=1200:*",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Tokyo, Japan",
    "purpose": "rent",
    "about_property": "This stylish modern apartment in Tokyo offers a blend of comfort and convenience. Located in a vibrant district, it is close to shops, restaurants, and public transport.",
    "rating": 4.8,
    "price": 3000
  },
  {
    "id": 54,
    "description": "Barcelona, Spain - Contemporary apartment with a sunny terrace.",
    "permission": "yes",
    "authority": null,
    "type": "apartment",
    "bedroom": 3,
    "bathroom": 2,
    "square_fit": 1400,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcbl3cgHNUMf-ufmoX6VZeqfya4LGld_Bidw&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Barcelona, Spain",
    "purpose": "sell",
    "about_property": "This contemporary apartment in Barcelona features a sunny terrace and modern amenities. It is located close to the beach and local attractions, making it a perfect vacation home.",
    "rating": 4.6,
    "price": 800000
  },
  {
    "id": 55,
    "description": "Montreal, Canada - Spacious apartment with stunning city views.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 2,
    "bathroom": 2,
    "square_fit": 1400,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXWVwT_nAxh4mm4U0Zr-SaINd0JhwE2lLTuA&s",
    "imageThree": "https://example.com/images/ny_loft.jpg",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Montreal, Canada",
    "purpose": "rent",
    "about_property": "This spacious apartment in Montreal offers stunning views of the city skyline. It features modern finishes and is located in a vibrant neighborhood with access to public transport.",
    "rating": 4.7,
    "price": 3500
  },
  {
    "id": 56,
    "description": "Singapore - Luxury apartment in the heart of the city.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 2,
    "bathroom": 2,
    "square_fit": 1500,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://i0.wp.com/withinthegrove.com/wp-content/uploads/2022/03/Small-Apartment-Living-Room-36.jpg?resize=750%2C562&ssl=1",
    "imageThree": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd2pyTtjxxd4KnvmrgplXdJ46OFcdcjKS_GA&s",
    "imageFour": "https://example.com/images/ny_loft.jpg",    
    "location": "Singapore",
    "purpose": "sell",
    "about_property": "This luxury apartment in Singapore features high-end finishes and amenities. It is centrally located, providing easy access to shops, restaurants, and public transport.",
    "rating": 4.8,
    "price": 2000000
  },
  {
    "id": 57,
    "description": "Sofia, Bulgaria - Modern apartment with a large terrace.",
    "permission": null,
    "authority": null,
    "type": "apartment",
    "bedroom": 2,
    "bathroom": 2,
    "square_fit": 1300,
    "imageOne": "https://example.com/images/ny_loft.jpg",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2rCZtU8_7UBxpZs5R9xnTyrh0GC0SGcMwGA&s",
    "imageThree": "https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2017/11/14/1/Original_Seth-Caplan-Stein13.jpg.rend.hgtvcom.1280.960.suffix/1510681412805.jpeg",
    "imageFour": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTisDuB-jEoUN_uGcf9eiTMNS3gWhlU0pvRmg&s",    
    "location": "Sofia, Bulgaria",
    "purpose": "rent",
    "about_property": "This modern apartment in Sofia features a large terrace perfect for entertaining. Located in a quiet neighborhood, it offers a peaceful living experience with easy access to the city.",
    "rating": 4.6,
    "price": 2200
  },
  {
    "id": 58,
    "description": "Prague, Czech Republic - Historic apartment with modern updates.",
    "permission": "yes",
    "authority": "verified",
    "type": "apartment",
    "bedroom": 1,
    "bathroom": 1,
    "square_fit": 800,
    "imageOne": "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
    "imageTwo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2heEAr62IA8aYpqsaA_EiI-cMDzmaKRZGIA&s",
    "imageThree": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmpWP1qCfV06HNIGsjI61XtUNJ0SnF2uQ1vg&s",
    "imageFour": "https://www.apartments.com/blog/sites/default/files/styles/x_large_hq/public/image/2023-06/ParkLine-apartment-in-Miami-FL.jpg?itok=kQmw64UU",
    "location": "Prague, Czech Republic",
    "purpose": "sell",
    "about_property": "This historic apartment in Prague has been updated with modern amenities while retaining its original charm. It is located in a prime area close to local attractions.",
    "rating": 4.9,
    "price": 450000
  }
]
  
export default PropertyData