const PropertyData = 

[
    {
      "id": 1,
      "description": "Dhaka, Bangladesh - Modern 3-bedroom apartment in Gulshan.",
      "permission": "yes",
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 500,
      "bedroom": 3,
      "bathroom": 2,
      "square_fit": 1200,
      "image": "apartment_gulshan_1.jpg"
    },
    {
      "id": 2,
      "description": "Toronto, Canada - Luxury penthouse overlooking Lake Ontario.",
      "permission": null,
      "authority": "verified",
      "type": "penthouse",
      "rent_per_month": 2500,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 2200,
      "image": "penthouse_toronto_2.jpg"
    },
    {
      "id": 3,
      "description": "Lagos, Nigeria - Spacious 5-bedroom duplex in Victoria Island.",
      "permission": "yes",
      "authority": null,
      "type": "duplex",
      "rent_per_month": 1500,
      "bedroom": 5,
      "bathroom": 4,
      "square_fit": 3000,
      "image": "duplex_lagos_3.jpg"
    },
    {
      "id": 4,
      "description": "New York, US - Stylish 2-bedroom apartment in Manhattan.",
      "permission": "yes",
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 3200,
      "bedroom": 2,
      "bathroom": 2,
      "square_fit": 1000,
      "image": "apartment_ny_4.jpg"
    },
    {
      "id": 5,
      "description": "London, UK - Elegant 3-bedroom luxury flat in Kensington.",
      "permission": null,
      "authority": "verified",
      "type": "luxury",
      "rent_per_month": 4500,
      "bedroom": 3,
      "bathroom": 3,
      "square_fit": 1800,
      "image": "luxury_london_5.jpg"
    },
    {
      "id": 6,
      "description": "Chittagong, Bangladesh - Cozy 2-bedroom apartment in Agrabad.",
      "permission": "yes",
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 300,
      "bedroom": 2,
      "bathroom": 1,
      "square_fit": 900,
      "image": "apartment_chittagong_6.jpg"
    },
    {
      "id": 7,
      "description": "Vancouver, Canada - Modern duplex with garden view.",
      "permission": "yes",
      "authority": null,
      "type": "duplex",
      "rent_per_month": 1800,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 2500,
      "image": "duplex_vancouver_7.jpg"
    },
    {
      "id": 8,
      "description": "Abuja, Nigeria - Contemporary 4-bedroom apartment in Garki.",
      "permission": null,
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 1200,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 2000,
      "image": "apartment_abuja_8.jpg"
    },
    {
      "id": 9,
      "description": "San Francisco, US - Penthouse with Golden Gate views.",
      "permission": "yes",
      "authority": "verified",
      "type": "penthouse",
      "rent_per_month": 5200,
      "bedroom": 3,
      "bathroom": 2,
      "square_fit": 2100,
      "image": "penthouse_sf_9.jpg"
    },
    {
      "id": 10,
      "description": "Birmingham, UK - Newly renovated duplex near city center.",
      "permission": "yes",
      "authority": null,
      "type": "duplex",
      "rent_per_month": 1300,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 1700,
      "image": "duplex_birmingham_10.jpg"
    },
    {
      "id": 11,
      "description": "Dhaka, Bangladesh - Luxury 4-bedroom penthouse in Banani.",
      "permission": "yes",
      "authority": "verified",
      "type": "penthouse",
      "rent_per_month": 2000,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 2500,
      "image": "penthouse_banani_11.jpg"
    },
    {
      "id": 12,
      "description": "Montreal, Canada - 3-bedroom apartment near downtown.",
      "permission": "yes",
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 1400,
      "bedroom": 3,
      "bathroom": 2,
      "square_fit": 1100,
      "image": "apartment_montreal_12.jpg"
    },
    {
      "id": 13,
      "description": "Ibadan, Nigeria - 2-bedroom apartment in a gated community.",
      "permission": null,
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 600,
      "bedroom": 2,
      "bathroom": 2,
      "square_fit": 850,
      "image": "apartment_ibadan_13.jpg"
    },
    {
      "id": 14,
      "description": "Los Angeles, US - Chic 2-bedroom luxury apartment in Beverly Hills.",
      "permission": "yes",
      "authority": "verified",
      "type": "luxury",
      "rent_per_month": 4800,
      "bedroom": 2,
      "bathroom": 2,
      "square_fit": 1300,
      "image": "luxury_la_14.jpg"
    },
    {
      "id": 15,
      "description": "Manchester, UK - Spacious building with multiple units for rent.",
      "permission": null,
      "authority": "verified",
      "type": "building",
      "rent_per_month": 6500,
      "bedroom": 10,
      "bathroom": 8,
      "square_fit": 4500,
      "image": "building_manchester_15.jpg"
    },
    {
      "id": 16,
      "description": "Rajshahi, Bangladesh - Affordable 3-bedroom apartment in a quiet area.",
      "permission": "yes",
      "authority": "verified",
      "type": "apartment",
      "rent_per_month": 350,
      "bedroom": 3,
      "bathroom": 2,
      "square_fit": 1150,
      "image": "apartment_rajshahi_16.jpg"
    },
    {
      "id": 17,
      "description": "Calgary, Canada - Family-friendly 5-bedroom duplex near parks.",
      "permission": null,
      "authority": "verified",
      "type": "duplex",
      "rent_per_month": 2000,
      "bedroom": 5,
      "bathroom": 4,
      "square_fit": 2600,
      "image": "duplex_calgary_17.jpg"
    },
    {
      "id": 18,
      "description": "Kano, Nigeria - 4-bedroom apartment in a secure complex.",
      "permission": "yes",
      "authority": null,
      "type": "apartment",
      "rent_per_month": 1000,
      "bedroom": 4,
      "bathroom": 3,
      "square_fit": 2000,
      "image": "apartment_kano_18.jpg"
    },
    {
      "id": 19,
      "description": "Houston, US - Modern penthouse in the heart of downtown.",
      "permission": "yes",
      "authority": "verified",
      "type": "penthouse",
      "rent_per_month": 4700,
      "bedroom": 3,
      "bathroom": 2,
      "square_fit": 2300,
      "image": "penthouse_houston_19.jpg"
    },
    {
      "id": 20,
      "description": "Edinburgh, UK - Historic building with luxury apartments.",
      "permission": "yes",
      "authority": null,
      "type": "building",
      "rent_per_month": 5200,
      "bedroom": 8,
      "bathroom": 6,
      "square_fit": 4000,
      "image": "building_edinburgh_20.jpg"
    },
    {
        "id": 21,
        "description": "Sylhet, Bangladesh - 2-bedroom apartment with scenic views.",
        "permission": "yes",
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 300,
        "bedroom": 2,
        "bathroom": 1,
        "square_fit": 800,
        "image": "apartment_sylhet_21.jpg"
      },
      {
        "id": 22,
        "description": "Ottawa, Canada - Duplex with open concept living and dining area.",
        "permission": null,
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 2200,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2700,
        "image": "duplex_ottawa_22.jpg"
      },
      {
        "id": 23,
        "description": "Port Harcourt, Nigeria - Luxurious apartment in a serene environment.",
        "permission": "yes",
        "authority": null,
        "type": "luxury",
        "rent_per_month": 1700,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2500,
        "image": "luxury_portharcourt_23.jpg"
      },
      {
        "id": 24,
        "description": "Miami, US - Beachfront 3-bedroom penthouse with ocean views.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 6200,
        "bedroom": 3,
        "bathroom": 3,
        "square_fit": 2700,
        "image": "penthouse_miami_24.jpg"
      },
      {
        "id": 25,
        "description": "Glasgow, UK - 4-bedroom building in a prime commercial area.",
        "permission": null,
        "authority": "verified",
        "type": "building",
        "rent_per_month": 7000,
        "bedroom": 6,
        "bathroom": 5,
        "square_fit": 3700,
        "image": "building_glasgow_25.jpg"
      },
      {
        "id": 26,
        "description": "Khulna, Bangladesh - Modern 3-bedroom apartment near the city center.",
        "permission": "yes",
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 400,
        "bedroom": 3,
        "bathroom": 2,
        "square_fit": 1100,
        "image": "apartment_khulna_26.jpg"
      },
      {
        "id": 27,
        "description": "Quebec City, Canada - Spacious duplex with private backyard.",
        "permission": null,
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 1900,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2400,
        "image": "duplex_quebec_27.jpg"
      },
      {
        "id": 28,
        "description": "Enugu, Nigeria - Newly built 3-bedroom apartment in a quiet neighborhood.",
        "permission": "yes",
        "authority": null,
        "type": "apartment",
        "rent_per_month": 850,
        "bedroom": 3,
        "bathroom": 2,
        "square_fit": 1200,
        "image": "apartment_enugu_28.jpg"
      },
      {
        "id": 29,
        "description": "Chicago, US - Luxury 5-bedroom penthouse in the heart of downtown.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 5400,
        "bedroom": 5,
        "bathroom": 4,
        "square_fit": 3000,
        "image": "penthouse_chicago_29.jpg"
      },
      {
        "id": 30,
        "description": "Liverpool, UK - Modern building with multiple residential units.",
        "permission": null,
        "authority": "verified",
        "type": "building",
        "rent_per_month": 7200,
        "bedroom": 12,
        "bathroom": 10,
        "square_fit": 5000,
        "image": "building_liverpool_30.jpg"
      },
      {
        "id": 31,
        "description": "Barisal, Bangladesh - Affordable 2-bedroom apartment near the river.",
        "permission": "yes",
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 250,
        "bedroom": 2,
        "bathroom": 1,
        "square_fit": 850,
        "image": "apartment_barisal_31.jpg"
      },
      {
        "id": 32,
        "description": "Winnipeg, Canada - Family-friendly duplex in a quiet suburb.",
        "permission": null,
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 1600,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2200,
        "image": "duplex_winnipeg_32.jpg"
      },
      {
        "id": 33,
        "description": "Kano, Nigeria - Luxury apartment with a large terrace.",
        "permission": "yes",
        "authority": "verified",
        "type": "luxury",
        "rent_per_month": 1800,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2300,
        "image": "luxury_kano_33.jpg"
      },
      {
        "id": 34,
        "description": "Seattle, US - Penthouse with panoramic city views.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 6100,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2600,
        "image": "penthouse_seattle_34.jpg"
      },
      {
        "id": 35,
        "description": "Oxford, UK - Historic building converted into modern apartments.",
        "permission": null,
        "authority": "verified",
        "type": "building",
        "rent_per_month": 5300,
        "bedroom": 6,
        "bathroom": 5,
        "square_fit": 4200,
        "image": "building_oxford_35.jpg"
      },
      {
        "id": 36,
        "description": "Mymensingh, Bangladesh - Compact 1-bedroom apartment in a residential area.",
        "permission": "yes",
        "authority": null,
        "type": "apartment",
        "rent_per_month": 200,
        "bedroom": 1,
        "bathroom": 1,
        "square_fit": 700,
        "image": "apartment_mymensingh_36.jpg"
      },
      {
        "id": 37,
        "description": "Halifax, Canada - 3-bedroom duplex near the waterfront.",
        "permission": "yes",
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 2100,
        "bedroom": 3,
        "bathroom": 2,
        "square_fit": 1500,
        "image": "duplex_halifax_37.jpg"
      },
      {
        "id": 38,
        "description": "Benin City, Nigeria - Contemporary 2-bedroom luxury apartment.",
        "permission": null,
        "authority": "verified",
        "type": "luxury",
        "rent_per_month": 950,
        "bedroom": 2,
        "bathroom": 2,
        "square_fit": 1200,
        "image": "luxury_benin_38.jpg"
      },
      {
        "id": 39,
        "description": "Dallas, US - Spacious 4-bedroom duplex in a gated community.",
        "permission": "yes",
        "authority": null,
        "type": "duplex",
        "rent_per_month": 3400,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2400,
        "image": "duplex_dallas_39.jpg"
      },
      {
        "id": 40,
        "description": "Brighton, UK - Stunning penthouse with sea views.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 4600,
        "bedroom": 3,
        "bathroom": 2,
        "square_fit": 2100,
        "image": "penthouse_brighton_40.jpg"
      },
      {
        "id": 41,
        "description": "Comilla, Bangladesh - Newly built 3-bedroom apartment near the market.",
        "permission": "yes",
        "authority": null,
        "type": "apartment",
        "rent_per_month": 350,
        "bedroom": 3,
        "bathroom": 2,
        "square_fit": 1050,
        "image": "apartment_comilla_41.jpg"
      },
      {
        "id": 42,
        "description": "Edmonton, Canada - Luxury duplex with modern finishes.",
        "permission": "yes",
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 2400,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2500,
        "image": "duplex_edmonton_42.jpg"
      },
      {
        "id": 43,
        "description": "Ibadan, Nigeria - Affordable 1-bedroom apartment in a secure estate.",
        "permission": "yes",
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 500,
        "bedroom": 1,
        "bathroom": 1,
        "square_fit": 700,
        "image": "apartment_ibadan_43.jpg"
      },
      {
        "id": 44,
        "description": "Boston, US - Modern 2-bedroom apartment with river views.",
        "permission": null,
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 3700,
        "bedroom": 2,
        "bathroom": 2,
        "square_fit": 1300,
        "image": "apartment_boston_44.jpg"
      },
      {
        "id": 45,
        "description": "Leeds, UK - Renovated building with multiple luxury units.",
        "permission": "yes",
        "authority": null,
        "type": "building",
        "rent_per_month": 6000,
        "bedroom": 10,
        "bathroom": 8,
        "square_fit": 4300,
        "image": "building_leeds_45.jpg"
      },
      {
        "id": 46,
        "description": "Rangpur, Bangladesh - Comfortable 2-bedroom apartment near the park.",
        "permission": "yes",
        "authority": "verified",
        "type": "apartment",
        "rent_per_month": 250,
        "bedroom": 2,
        "bathroom": 1,
        "square_fit": 900,
        "image": "apartment_rangpur_46.jpg"
      },
      {
        "id": 47,
        "description": "Toronto, Canada - Luxury penthouse in a high-rise building.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 7200,
        "bedroom": 5,
        "bathroom": 4,
        "square_fit": 3200,
        "image": "penthouse_toronto_47.jpg"
      },
      {
        "id": 48,
        "description": "Abuja, Nigeria - Duplex with private garden and pool.",
        "permission": "yes",
        "authority": "verified",
        "type": "duplex",
        "rent_per_month": 3000,
        "bedroom": 4,
        "bathroom": 4,
        "square_fit": 2800,
        "image": "duplex_abuja_48.jpg"
      },
      {
        "id": 49,
        "description": "Los Angeles, US - Ultra-modern 6-bedroom luxury penthouse.",
        "permission": "yes",
        "authority": "verified",
        "type": "luxury",
        "rent_per_month": 15000,
        "bedroom": 6,
        "bathroom": 6,
        "square_fit": 4000,
        "image": "luxury_losangeles_49.jpg"
      },
      {
        "id": 50,
        "description": "London, UK - Luxury penthouse with views of the Thames River.",
        "permission": "yes",
        "authority": "verified",
        "type": "penthouse",
        "rent_per_month": 9000,
        "bedroom": 4,
        "bathroom": 3,
        "square_fit": 2800,
        "image": "penthouse_london_50.jpg"
      }
    
    
  ]
  
export default PropertyData